/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { mapRecordTypeFields } from "./mapRecordTypeFields";
import { previewRecordTypeFields } from "./previewRecordTypeFields";
import { previewRecordTypeFieldValues } from "./previewRecordTypeFieldValues";
import { selectBulkJob } from "./selectBulkJob";
import { selectContact } from "./selectContact";
import { selectCustomer } from "./selectCustomer";
import { selectFlow } from "./selectFlow";
import { selectLead } from "./selectLead";
import { selectOpportunity } from "./selectOpportunity";
import { selectOutboundMessage } from "./selectOutboundMessage";
import { selectProfile } from "./selectProfile";
import { selectRecordType } from "./selectRecordType";
import { selectRecordTypes } from "./selectRecordTypes";
import { selectRecordTypesWithFields } from "./selectRecordTypesWithFields";
import { selectUser } from "./selectUser";

export default {
  mapRecordTypeFields,
  previewRecordTypeFields,
  previewRecordTypeFieldValues,
  selectBulkJob,
  selectContact,
  selectCustomer,
  selectFlow,
  selectLead,
  selectOpportunity,
  selectOutboundMessage,
  selectProfile,
  selectRecordType,
  selectRecordTypes,
  selectRecordTypesWithFields,
  selectUser,
};
