/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Mapping Fields
   *
   */
  mappingFields: never;
  /**
   * Selected Record Types
   *
   */
  objectSelection: never;
  /**
   * Include Supplemental Metadata
   *
   * @default false
   */
  includeSupplementalMetadata?: boolean;
}

/**
 * Map Record Type Fields
 *
 * @description A map of a list of fields to Salesforce Record Type fields.
 * This object is used to support type hinting.
 */
export const mapRecordTypeFields = {
  key: "mapRecordTypeFields",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "objectFieldMap",
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    mappingFields: {
      inputType: "objectFieldMap",
      collection: undefined,
      default: `null`,
      required: true,
    },
    objectSelection: {
      inputType: "objectSelection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    includeSupplementalMetadata: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
  },
} as const;

/**
 * Map Record Type Fields DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const salesforceMapRecordTypeFields = (
  stableKey: string,
  values: {
    version?: { value: string } | TemplateExpression | ConfigVarExpression;
    connection: ConfigVarExpression;
    mappingFields: { value: never } | TemplateExpression | ConfigVarExpression;
    objectSelection:
      | { value: never }
      | TemplateExpression
      | ConfigVarExpression;
    includeSupplementalMetadata?:
      | { value: boolean }
      | TemplateExpression
      | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "salesforce",
          true,
          context.componentRegistry
        );
      },
      key: "mapRecordTypeFields",
      values,
    },
  });
};
