/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Record Type
   *
   */
  dynamicRecordType: never;
}

/**
 * Preview Record Type Fields
 *
 * @description A list of fields of the specified Record Type for use as a preview during configuration.
 * This object is used to support type hinting.
 */
export const previewRecordTypeFields = {
  key: "previewRecordTypeFields",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    dynamicRecordType: {
      inputType: "dynamicObjectSelection",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * Preview Record Type Fields DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const salesforcePreviewRecordTypeFields = (
  stableKey: string,
  values: {
    version?: { value: string } | TemplateExpression | ConfigVarExpression;
    connection: ConfigVarExpression;
    dynamicRecordType:
      | { value: never }
      | TemplateExpression
      | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "salesforce",
          true,
          context.componentRegistry
        );
      },
      key: "previewRecordTypeFields",
      values,
    },
  });
};
