/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Record Type
   *
   */
  dynamicRecordType: never;
  /**
   * Field Name
   *
   */
  dynamicFieldName: never;
  /**
   * Value Count
   *
   * @default 5
   */
  valueCount?: string;
}

/**
 * Preview Record Type Field Values
 *
 * @description A list of values of the specified Record Type field for use as a preview during configuration.
 * This object is used to support type hinting.
 */
export const previewRecordTypeFieldValues = {
  key: "previewRecordTypeFieldValues",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    dynamicRecordType: {
      inputType: "dynamicObjectSelection",
      collection: undefined,
      default: ``,
      required: true,
    },
    dynamicFieldName: {
      inputType: "dynamicFieldSelection",
      collection: undefined,
      default: ``,
      required: true,
    },
    valueCount: {
      inputType: "string",
      collection: undefined,
      default: `5`,
    },
  },
} as const;

/**
 * Preview Record Type Field Values DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const salesforcePreviewRecordTypeFieldValues = (
  stableKey: string,
  values: {
    version?: { value: string } | TemplateExpression | ConfigVarExpression;
    connection: ConfigVarExpression;
    dynamicRecordType:
      | { value: never }
      | TemplateExpression
      | ConfigVarExpression;
    dynamicFieldName:
      | { value: never }
      | TemplateExpression
      | ConfigVarExpression;
    valueCount?: { value: string } | TemplateExpression | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "salesforce",
          true,
          context.componentRegistry
        );
      },
      key: "previewRecordTypeFieldValues",
      values,
    },
  });
};
