/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Filter Query
   *
   */
  filterQuery?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Select Profile
 *
 * @description A picklist of profiles in the Salesforce org.
 * This object is used to support type hinting.
 */
export const selectProfile = {
  key: "selectProfile",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    filterQuery: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
} as const;

/**
 * Select Profile DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const salesforceSelectProfile = (
  stableKey: string,
  values: {
    version?: { value: string } | TemplateExpression | ConfigVarExpression;
    filterQuery?: { value: string } | TemplateExpression | ConfigVarExpression;
    connection: ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "salesforce",
          true,
          context.componentRegistry
        );
      },
      key: "selectProfile",
      values,
    },
  });
};
