/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Default Selected Record Types
   *
   */
  defaultSelectedRecordTypes?: Array<string>;
  /**
   * Record Type Filter
   *
   */
  recordTypeFilter: Array<string>;
  /**
   * Include All Custom Record Types
   *
   * @default true
   */
  includeAllCustomRecordTypes?: boolean;
  /**
   * Include Only Top Level Record Types
   *
   * @default false
   */
  includeOnlyTopLevelRecordTypes?: boolean;
  /**
   * Show Triggerable Only
   *
   * @default false
   */
  showTriggerableOnly?: boolean;
}

/**
 * Select Record Type With Fields
 *
 * @description A picklist of available Salesforce Record Types with their associated fields.
 * This object is used to support type hinting.
 */
export const selectRecordTypesWithFields = {
  key: "selectRecordTypesWithFields",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "objectSelection",
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    defaultSelectedRecordTypes: {
      inputType: "string",
      collection: "valuelist",
      default: [],
    },
    recordTypeFilter: {
      inputType: "string",
      collection: "valuelist",
      default: [],
      required: true,
    },
    includeAllCustomRecordTypes: {
      inputType: "boolean",
      collection: undefined,
      default: `true`,
    },
    includeOnlyTopLevelRecordTypes: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    showTriggerableOnly: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
  },
} as const;

/**
 * Select Record Type With Fields DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const salesforceSelectRecordTypesWithFields = (
  stableKey: string,
  values: {
    version?: { value: string } | TemplateExpression | ConfigVarExpression;
    connection: ConfigVarExpression;
    defaultSelectedRecordTypes?:
      | { value: Array<string> }
      | TemplateExpression
      | ConfigVarExpression;
    recordTypeFilter:
      | { value: Array<string> }
      | TemplateExpression
      | ConfigVarExpression;
    includeAllCustomRecordTypes?:
      | { value: boolean }
      | TemplateExpression
      | ConfigVarExpression;
    includeOnlyTopLevelRecordTypes?:
      | { value: boolean }
      | TemplateExpression
      | ConfigVarExpression;
    showTriggerableOnly?:
      | { value: boolean }
      | TemplateExpression
      | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "salesforce",
          true,
          context.componentRegistry
        );
      },
      key: "selectRecordTypesWithFields",
      values,
    },
  });
};
