/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import actions from "./actions";
import connections from "./connections";
import dataSources from "./dataSources";
import triggers from "./triggers";

export { actions, connections, dataSources, triggers };

export default {
  key: "google-drive",
  public: true,
  signature: "dde3469ed91c732065213124abbdf6d4d084630a",
  actions,
  dataSources,
  connections,
  triggers,
} as const;
