/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import actions from "./actions";
import connections from "./connections";
import dataSources from "./dataSources";
import triggers from "./triggers";

export { actions, connections, dataSources, triggers };

export default {
  key: "salesforce",
  public: true,
  signature: "107f47e768d1da98dd3606466cc7700911be0cbb",
  actions,
  dataSources,
  connections,
  triggers,
} as const;
