/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface BasicValues {
  /**
   * Username
   *
   */
  username: string;
  /**
   * Password
   *
   */
  password: string;
  /**
   * Login URL
   *
   */
  loginUrl: string;
}

/**
 * Basic Authentication
 *
 * @comments Authenticate requests using Basic Authentication.
 * This object is used to support type hinting.
 */
export const basic = {
  key: "basic",
  perform: (_values: BasicValues): Promise<void> => Promise.resolve(),
  inputs: {
    username: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    password: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
    loginUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * Basic Authentication Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const salesforceBasic = (
  stableKey: string,
  values: {
    username: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    password: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    loginUrl: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  }
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "salesforce",
          true,
          context.componentRegistry
        );
      },
      key: "basic",
      values,
    },
  });
};
