/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type {
  CustomerActivatedConnectionConfigVar,
  OrganizationActivatedConnectionConfigVar,
} from "@prismatic-io/spectral";
import { basic } from "./basic";
import { oauth2 } from "./oauth2";
import { salesforceClientCredentials } from "./salesforceClientCredentials";

export default {
  basic,
  oauth2,
  salesforceClientCredentials,
};
export const salesforceReusableConnection = (
  stableKey: "salesforce-demo" | (string & {})
):
  | OrganizationActivatedConnectionConfigVar
  | CustomerActivatedConnectionConfigVar => ({
  stableKey,
  dataType: "connection",
});
