/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface Oauth2Values {
  /**
   * Authorize URL
   *
   * @default https:\/\/login.salesforce.com\/services\/oauth2\/authorize
   */
  authorizeUrl?: string;
  /**
   * Token URL
   *
   * @default https:\/\/login.salesforce.com\/services\/oauth2\/token
   */
  tokenUrl?: string;
  /**
   * Revoke URL
   *
   * @default https:\/\/login.salesforce.com\/services\/oauth2\/revoke
   */
  revokeUrl?: string;
  /**
   * Consumer Key
   *
   */
  clientId: string;
  /**
   * Consumer Secret
   *
   */
  clientSecret: string;
}

/**
 * OAuth 2.0
 *
 * @comments Authenticate requests using OAuth 2.0.
 * This object is used to support type hinting.
 */
export const oauth2 = {
  key: "oauth2",
  perform: (_values: Oauth2Values): Promise<void> => Promise.resolve(),
  inputs: {
    authorizeUrl: {
      inputType: "string",
      collection: undefined,
      default: `https:\/\/login.salesforce.com\/services\/oauth2\/authorize`,
    },
    tokenUrl: {
      inputType: "string",
      collection: undefined,
      default: `https:\/\/login.salesforce.com\/services\/oauth2\/token`,
    },
    revokeUrl: {
      inputType: "string",
      collection: undefined,
      default: `https:\/\/login.salesforce.com\/services\/oauth2\/revoke`,
    },
    clientId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    clientSecret: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * OAuth 2.0 Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const salesforceOauth2 = (
  stableKey: string,
  values: {
    authorizeUrl?: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    tokenUrl?: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    revokeUrl?: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    clientId: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    clientSecret: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  }
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "salesforce",
          true,
          context.componentRegistry
        );
      },
      key: "oauth2",
      values,
    },
  });
};
