/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface SalesforceClientCredentialsValues {
  /**
   * Instance URL
   *
   */
  instanceUrl: string;
  /**
   * Consumer Key
   *
   */
  clientId: string;
  /**
   * Consumer Secret
   *
   */
  clientSecret: string;
  /**
   * Scopes
   *
   */
  scopes?: string;
}

/**
 * OAuth 2.0 Client Credentials
 *
 * @comments Authenticate using OAuth 2.0 Client Credentials for server-to-server integration.
 * This object is used to support type hinting.
 */
export const salesforceClientCredentials = {
  key: "salesforceClientCredentials",
  perform: (_values: SalesforceClientCredentialsValues): Promise<void> =>
    Promise.resolve(),
  inputs: {
    instanceUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    clientId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    clientSecret: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
    scopes: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;

/**
 * OAuth 2.0 Client Credentials Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const salesforceSalesforceClientCredentials = (
  stableKey: string,
  values: {
    instanceUrl: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    clientId: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    clientSecret: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    scopes?: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  }
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "salesforce",
          true,
          context.componentRegistry
        );
      },
      key: "salesforceClientCredentials",
      values,
    },
  });
};
