/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface AbortBulkQueryJobValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Query Job ID
   *
   */
  queryJobId: string;
}

/**
 * Abort Bulk Query Job
 *
 * @description Abort a bulk query job.
 */
export const abortBulkQueryJob = {
  key: "abortBulkQueryJob",
  perform: async <TReturn>(
    values: AbortBulkQueryJobValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.abortBulkQueryJob({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    queryJobId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      id: "750R000000146UvIAI",
      state: "Aborted",
      object: "Account",
      operation: "query",
      apiVersion: 46,
      contentType: "CSV",
      createdById: "005R0000000GiwjIAC",
      createdDate: "2018-12-18T16:15:31.000+0000",
      systemModstamp: "2018-12-18T16:15:32.000+0000",
      concurrencyMode: "Parallel",
    },
  },
} as const;
