/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface AddAttachmentValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record ID
   *
   */
  recordId: string;
  /**
   * File Name
   *
   */
  fileName: string;
  /**
   * File Contents
   *
   */
  file: string;
}

/**
 * Add Attachment
 *
 * @description Attach a file to a parent record object (Account, Opportunity, etc.).
 */
export const addAttachment = {
  key: "addAttachment",
  perform: async <TReturn>(values: AddAttachmentValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.addAttachment({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fileName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    file: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "015D0000000N3ZZIA0", errors: [], success: true },
  },
} as const;
