/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface AddUserPermissionSetValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * User Name
   *
   */
  userName: string;
  /**
   * Permission Set
   *
   */
  permissionName: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Add User Permission Set
 *
 * @description Add a permission set to the specified user.
 */
export const addUserPermissionSet = {
  key: "addUserPermissionSet",
  perform: async <TReturn>(
    values: AddUserPermissionSetValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.addUserPermissionSet({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    userName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    permissionName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
