/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface BulkInsertRecordsValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record Type
   *
   */
  recordType: string;
  /**
   * External ID Field Name
   *
   */
  externalIdFieldName: string;
  /**
   * File
   *
   */
  file: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Bulk Insert Records
 *
 * @description Create new Salesforce records in bulk.
 */
export const bulkInsertRecords = {
  key: "bulkInsertRecords",
  perform: async <TReturn>(
    values: BulkInsertRecordsValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.bulkInsertRecords({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    externalIdFieldName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    file: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: [{ id: "015D0000000N3ZZIA0", errors: [], success: true }],
  },
} as const;
