/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CompositeRequestsValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * All Or None
   *
   * @default true
   */
  allOrNone?: boolean;
  /**
   * Collate Subrequests
   *
   * @default false
   */
  collateSubrequests?: boolean;
  /**
   * Composite Request
   *
   */
  compositeRequest: string;
}

/**
 * Send Composite Request
 *
 * @description Send multiple requests in a single HTTP call.
 */
export const compositeRequests = {
  key: "compositeRequests",
  perform: async <TReturn>(
    values: CompositeRequestsValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.compositeRequests({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    allOrNone: {
      inputType: "boolean",
      collection: undefined,
      default: `true`,
    },
    collateSubrequests: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    compositeRequest: {
      inputType: "code",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      results: [
        { result: null, statusCode: 204 },
        {
          result: {
            Id: "001D000000K0fXOIAZ",
            Name: "NewName",
            attributes: {
              url: "/services/data/v60.0/sobjects/Account/001D000000K0fXOIAZ",
              type: "Account",
            },
            BillingPostalCode: "94105",
          },
          statusCode: 200,
        },
      ],
      hasErrors: false,
    },
  },
} as const;
