/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateCustomerValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Name
   *
   */
  name: string;
  /**
   * Party ID
   *
   */
  partyId: string;
  /**
   * Customer Status Type
   *
   * @default Active
   */
  customerStatusType?: string;
  /**
   * Last Reference Date
   *
   */
  lastReferenceDate?: string;
  /**
   * Last Viewed Date
   *
   */
  lastViewedDate?: string;
  /**
   * Owner ID
   *
   */
  ownerId?: string;
  /**
   * Total Lifetime Value
   *
   */
  totalLifeTimeValue?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Create Customer
 *
 * @description Create a Salesforce customer.
 */
export const createCustomer = {
  key: "createCustomer",
  perform: async <TReturn>(values: CreateCustomerValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.createCustomer({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    name: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    partyId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    customerStatusType: {
      inputType: "string",
      collection: undefined,
      default: `Active`,
    },
    lastReferenceDate: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    lastViewedDate: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    ownerId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    totalLifeTimeValue: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
