/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateProfileValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Name
   *
   */
  name: string;
  /**
   * Description
   *
   */
  description: string;
  /**
   * Permissions
   *
   */
  permissions?: string;
  /**
   * User License
   *
   */
  userLicense: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Create Profile
 *
 * @description Create a Salesforce profile.
 */
export const createProfile = {
  key: "createProfile",
  perform: async <TReturn>(values: CreateProfileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.createProfile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    name: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    description: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    permissions: {
      inputType: "data",
      collection: undefined,
      default: ``,
    },
    userLicense: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
