/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateUserValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Profile
   *
   */
  profile: string;
  /**
   * User Name
   *
   */
  userName: string;
  /**
   * First Name
   *
   */
  firstName?: string;
  /**
   * Last Name
   *
   */
  lastName?: string;
  /**
   * Time Zone
   *
   */
  timeZone: string;
  /**
   * Alias
   *
   */
  alias: string;
  /**
   * Email Address
   *
   */
  email: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Create User
 *
 * @description Create a Salesforce user.
 */
export const createUser = {
  key: "createUser",
  perform: async <TReturn>(values: CreateUserValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.createUser({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    profile: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    userName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    firstName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    lastName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    timeZone: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    alias: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    email: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
