/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateWorkflowRuleValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record Type
   *
   */
  recordType: string;
  /**
   * Rule Name
   *
   */
  ruleName: string;
  /**
   * Trigger Type
   *
   * @default onAllChanges
   */
  triggerType?: string;
  /**
   * Active
   *
   * @default true
   */
  active?: boolean;
  /**
   * Description
   *
   */
  description?: string;
  /**
   * Rule Criteria Filter
   *
   */
  filterCriteria?: string;
  /**
   * Formula
   *
   */
  formulaInput?: string;
  /**
   * Outbound Message Actions
   *
   */
  outboundMessageActions?: Array<string>;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Create Workflow Rule
 *
 * @description Create a Workflow Rule. Workflow Rules are deprecated by Salesforce; migrate to Flow-based actions.
 */
export const createWorkflowRule = {
  key: "createWorkflowRule",
  perform: async <TReturn>(
    values: CreateWorkflowRuleValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.createWorkflowRule({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    ruleName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    triggerType: {
      inputType: "string",
      collection: undefined,
      default: `onAllChanges`,
    },
    active: {
      inputType: "boolean",
      collection: undefined,
      default: `true`,
    },
    description: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    filterCriteria: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    formulaInput: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    outboundMessageActions: {
      inputType: "string",
      collection: "valuelist",
      default: [],
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: { data: { success: true, fullName: "TestObject1__c" } },
} as const;
