/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateObjectsFromMetadataValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Metadata Type
   *
   * @default CustomObject
   */
  metadataType?: string;
  /**
   * Metadata
   *
   * @default [\\n  {\\n    \\"fullName\\": \\"TestObject1__c\\",\\n    \\"label\\": \\"Test Object 1\\",\\n    \\"pluralLabel\\": \\"Test Object 1\\",\\n    \\"nameField\\": {\\n      \\"type\\": \\"Text\\",\\n      \\"label\\": \\"Test Object Name\\"\\n    },\\n    \\"deploymentStatus\\": \\"Deployed\\",\\n    \\"sharingModel\\": \\"ReadWrite\\"\\n  }\\n]
   */
  metadata?: string;
}

/**
 * Create Metadata
 *
 * @description Create new metadata components.
 */
export const createObjectsFromMetadata = {
  key: "createObjectsFromMetadata",
  perform: async <TReturn>(
    values: CreateObjectsFromMetadataValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.createObjectsFromMetadata({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    metadataType: {
      inputType: "string",
      collection: undefined,
      default: `CustomObject`,
    },
    metadata: {
      inputType: "code",
      collection: undefined,
      default: `[
  {
    "fullName": "TestObject1__c",
    "label": "Test Object 1",
    "pluralLabel": "Test Object 1",
    "nameField": {
      "type": "Text",
      "label": "Test Object Name"
    },
    "deploymentStatus": "Deployed",
    "sharingModel": "ReadWrite"
  }
]`,
    },
  },
  examplePayload: { data: { success: true, fullName: "TestObject1__c" } },
} as const;
