/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateBulkJobValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Object
   *
   */
  object?: string;
  /**
   * Operation
   *
   * @default insert
   */
  operation?: string;
  /**
   * External ID Field Name
   *
   */
  externalIdFieldName?: string;
  /**
   * Assignment Rule ID
   *
   */
  assignmentRuleId?: string;
  /**
   * Column Delimiter
   *
   * @default COMMA
   */
  columnDelimiter?: string;
  /**
   * Line Ending
   *
   * @default LF
   */
  lineEnding?: string;
}

/**
 * Create Bulk Job
 *
 * @description Create a bulk ingest job representing an operation and its associated data for asynchronous processing in Salesforce.
 */
export const createBulkJob = {
  key: "createBulkJob",
  perform: async <TReturn>(values: CreateBulkJobValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.createBulkJob({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    object: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    operation: {
      inputType: "string",
      collection: undefined,
      default: `insert`,
    },
    externalIdFieldName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    assignmentRuleId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    columnDelimiter: {
      inputType: "string",
      collection: undefined,
      default: `COMMA`,
    },
    lineEnding: {
      inputType: "string",
      collection: undefined,
      default: `LF`,
    },
  },
  examplePayload: {
    data: {
      id: "750R0000000zlh9IAA",
      state: "JobComplete",
      object: "Account",
      jobType: "V2Query",
      retries: 0,
      operation: "query",
      apiVersion: 46,
      lineEnding: "LF",
      contentType: "CSV",
      createdById: "005R0000000GiwjIAC",
      createdDate: "2018-12-10T17:50:19.000+0000",
      systemModstamp: "2018-12-10T17:51:27.000+0000",
      columnDelimiter: "COMMA",
      concurrencyMode: "Parallel",
      totalProcessingTime: 334,
      isPkChunkingSupported: true,
      numberRecordsProcessed: 500,
    },
  },
} as const;
