/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateBulkQueryJobValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Operation
   *
   * @default query
   */
  operation?: string;
  /**
   * Query
   *
   */
  query: string;
  /**
   * Column Delimiter
   *
   * @default COMMA
   */
  columnDelimiter?: string;
  /**
   * Line Ending
   *
   * @default LF
   */
  lineEnding?: string;
}

/**
 * Create Bulk Query Job
 *
 * @description Create a bulk query job.
 */
export const createBulkQueryJob = {
  key: "createBulkQueryJob",
  perform: async <TReturn>(
    values: CreateBulkQueryJobValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.createBulkQueryJob({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    operation: {
      inputType: "string",
      collection: undefined,
      default: `query`,
    },
    query: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    columnDelimiter: {
      inputType: "string",
      collection: undefined,
      default: `COMMA`,
    },
    lineEnding: {
      inputType: "string",
      collection: undefined,
      default: `LF`,
    },
  },
  examplePayload: {
    data: {
      id: "750R0000000zlh9IAA",
      state: "UploadComplete",
      object: "Account",
      operation: "query",
      apiVersion: 46,
      lineEnding: "LF",
      contentType: "CSV",
      createdById: "005R0000000GiwjIAC",
      createdDate: "2018-12-10T17:50:19.000+0000",
      systemModstamp: "2018-12-10T17:50:19.000+0000",
      columnDelimiter: "COMMA",
      concurrencyMode: "Parallel",
    },
  },
} as const;
