/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateFieldsFromMetadataValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Metadata Type
   *
   * @default CustomField
   */
  metadataType?: string;
  /**
   * Metadata
   *
   * @default [\\n  {\\n    \\"fullName\\": \\"Contact.FieldName1__c\\",\\n    \\"label\\": \\"Field Name 1\\",\\n    \\"type\\": \\"Text\\",\\n    \\"length\\": 80,\\n    \\"inlineHelpText\\": \\"Text that appears in the ? next to a field.\\"\\n  }\\n]
   */
  metadata?: string;
}

/**
 * Create Metadata Fields
 *
 * @description Create custom fields from metadata.
 */
export const createFieldsFromMetadata = {
  key: "createFieldsFromMetadata",
  perform: async <TReturn>(
    values: CreateFieldsFromMetadataValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.createFieldsFromMetadata({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    metadataType: {
      inputType: "string",
      collection: undefined,
      default: `CustomField`,
    },
    metadata: {
      inputType: "code",
      collection: undefined,
      default: `[
  {
    "fullName": "Contact.FieldName1__c",
    "label": "Field Name 1",
    "type": "Text",
    "length": 80,
    "inlineHelpText": "Text that appears in the ? next to a field."
  }
]`,
    },
  },
  examplePayload: { data: { success: true, fullName: "TestObject1__c" } },
} as const;
