/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateWorkflowOutboundMessageValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record Type
   *
   */
  recordType: string;
  /**
   * Outbound Message Name
   *
   */
  name: string;
  /**
   * Description
   *
   */
  description?: string;
  /**
   * Endpoint URL
   *
   */
  endpointUrl: string;
  /**
   * Integration User Email
   *
   */
  integrationUserEmail?: string;
  /**
   * Fields
   *
   */
  fields?: Array<string>;
  /**
   * Dynamic Fields
   *
   */
  dynamicFields?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Create Outbound Message
 *
 * @description Create an Outbound Message in Salesforce.
 */
export const createWorkflowOutboundMessage = {
  key: "createWorkflowOutboundMessage",
  perform: async <TReturn>(
    values: CreateWorkflowOutboundMessageValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.createWorkflowOutboundMessage({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    name: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    description: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    endpointUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    integrationUserEmail: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fields: {
      inputType: "string",
      collection: "valuelist",
      default: [],
    },
    dynamicFields: {
      inputType: "data",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: { data: { success: true, fullName: "TestObject1__c" } },
} as const;
