/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateContactValues {
  /**
   * Email Address
   *
   */
  email: string;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Phone
   *
   */
  phone?: string;
  /**
   * First Name
   *
   */
  firstName?: string;
  /**
   * Last Name
   *
   */
  lastName?: string;
  /**
   * Department
   *
   */
  department?: string;
  /**
   * Birthdate
   *
   */
  birthdate?: string;
  /**
   * Fax
   *
   */
  fax?: string;
  /**
   * Title
   *
   */
  title?: string;
  /**
   * Mobile Phone
   *
   */
  mobile?: string;
  /**
   * Assistant
   *
   */
  assistant?: string;
  /**
   * Assistant's Phone
   *
   */
  assistantPhone?: string;
  /**
   * Description
   *
   */
  description?: string;
  /**
   * Billing City
   *
   */
  billingCity?: string;
  /**
   * Billing Postal Code
   *
   */
  billingPostalCode?: string;
  /**
   * Billing State
   *
   */
  billingState?: string;
  /**
   * Billing Street Address
   *
   */
  billingStreet?: string;
  /**
   * Billing Country
   *
   */
  billingCountry?: string;
  /**
   * Street Address
   *
   */
  street?: string;
  /**
   * State
   *
   */
  state?: string;
  /**
   * Country
   *
   */
  country?: string;
  /**
   * City
   *
   */
  city?: string;
  /**
   * Postal Code
   *
   */
  postalCode?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Create Contact
 *
 * @description Create a Salesforce contact.
 */
export const createContact = {
  key: "createContact",
  perform: async <TReturn>(values: CreateContactValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.createContact({
      ...values,
    })) as TReturn;
  },
  inputs: {
    email: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    phone: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    firstName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    lastName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    department: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    birthdate: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fax: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    title: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    mobile: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    assistant: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    assistantPhone: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    description: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    billingCity: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    billingPostalCode: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    billingState: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    billingStreet: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    billingCountry: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    street: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    state: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    country: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    city: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    postalCode: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
