/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeactivateFlowValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Flow Name
   *
   */
  flowName: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Deactivate Flow
 *
 * @description Deactivate a Flow in Salesforce by name.
 */
export const deactivateFlow = {
  key: "deactivateFlow",
  perform: async <TReturn>(values: DeactivateFlowValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.deactivateFlow({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    flowName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: { data: { errors: [], success: true, fullName: "My_Flow" } },
} as const;
