/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteWorkflowRuleValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Full Name Identifier
   *
   */
  fullName: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Delete Workflow Rule
 *
 * @description Delete a Workflow Rule. Workflow Rules are deprecated by Salesforce; migrate to Flow-based actions.
 */
export const deleteWorkflowRule = {
  key: "deleteWorkflowRule",
  perform: async <TReturn>(
    values: DeleteWorkflowRuleValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.deleteWorkflowRule({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    fullName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: { data: { success: true, fullName: "TestObject1__c" } },
} as const;
