/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteMetadataValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Metadata Type
   *
   * @default CustomObject
   */
  metadataType?: string;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Object Full Names
   *
   */
  fullNames: string;
}

/**
 * Delete Metadata
 *
 * @description Delete one or more metadata components.
 */
export const deleteMetadata = {
  key: "deleteMetadata",
  perform: async <TReturn>(values: DeleteMetadataValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.deleteMetadata({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    metadataType: {
      inputType: "string",
      collection: undefined,
      default: `CustomObject`,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    fullNames: {
      inputType: "code",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: { data: null },
} as const;
