/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteContactValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record ID
   *
   */
  recordId: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Delete Contact
 *
 * @description Delete an existing contact record.
 */
export const deleteContact = {
  key: "deleteContact",
  perform: async <TReturn>(values: DeleteContactValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.deleteContact({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
