/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteBulkJobValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Bulk Job ID
   *
   */
  bulkJobId: string;
}

/**
 * Delete Bulk Job
 *
 * @description Delete a bulk ingest job.
 */
export const deleteBulkJob = {
  key: "deleteBulkJob",
  perform: async <TReturn>(values: DeleteBulkJobValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.deleteBulkJob({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    bulkJobId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: { data: {} },
} as const;
