/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteWorkflowOutboundMessageValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Full Name Identifier
   *
   */
  fullName: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Delete Workflow Outbound Message
 *
 * @description Delete a Workflow Outbound Message.
 */
export const deleteWorkflowOutboundMessage = {
  key: "deleteWorkflowOutboundMessage",
  perform: async <TReturn>(
    values: DeleteWorkflowOutboundMessageValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.deleteWorkflowOutboundMessage({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    fullName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: { data: { success: true, fullName: "TestObject1__c" } },
} as const;
