/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteCustomerValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record ID
   *
   */
  recordId: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Delete Customer
 *
 * @description Delete an existing customer record.
 */
export const deleteCustomer = {
  key: "deleteCustomer",
  perform: async <TReturn>(values: DeleteCustomerValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.deleteCustomer({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: { data: { success: true, fullName: "TestObject1__c" } },
} as const;
