/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteAccountValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Record ID
   *
   */
  recordId: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Delete Account
 *
 * @description Delete an existing account record.
 */
export const deleteAccount = {
  key: "deleteAccount",
  perform: async <TReturn>(values: DeleteAccountValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.deleteAccount({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {},
} as const;
