/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteInstancedFlowsAndOutboundMessagesValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Endpoint URL
   *
   */
  endpointUrl: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Delete Instanced Flows and Outbound Messages
 *
 * @description Delete all instanced flows and outbound messages for a given endpoint URL.
 */
export const deleteInstancedFlowsAndOutboundMessages = {
  key: "deleteInstancedFlowsAndOutboundMessages",
  perform: async <TReturn>(
    values: DeleteInstancedFlowsAndOutboundMessagesValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.deleteInstancedFlowsAndOutboundMessages(
      { ...values }
    )) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    endpointUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      deletedFlows: ["My_Flow"],
      deletedOutboundMessages: ["My_Outbound_Message"],
    },
  },
} as const;
