/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DescribeObjectValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record Type
   *
   */
  recordType: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Describe Object
 *
 * @description Describe attributes of a Salesforce record type.
 */
export const describeObject = {
  key: "describeObject",
  perform: async <TReturn>(values: DescribeObjectValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.describeObject({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {},
} as const;
