/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DescribeCustomerSObjectValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Describe Customer SObject
 *
 * @description Describe metadata attributes of a Salesforce Customer object.
 */
export const describeCustomerSObject = {
  key: "describeCustomerSObject",
  perform: async <TReturn>(
    values: DescribeCustomerSObjectValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.describeCustomerSObject({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      name: "Customer",
      urls: {
        layouts: "/services/data/v53.0/sobjects/Customer/describe/layouts",
        sobject: "/services/data/v53.0/sobjects/Customer",
        describe: "/services/data/v53.0/sobjects/Customer/describe",
        rowTemplate: "/services/data/v53.0/sobjects/Customer/{ID}",
        uiNewRecord: "https://dummy-uri.my.salesforce.com/0o6/e",
        compactLayouts:
          "/services/data/v53.0/sobjects/Customer/describe/compactLayouts",
        uiEditTemplate: "https://dummy-uri.my.salesforce.com/{ID}/e",
        approvalLayouts:
          "/services/data/v53.0/sobjects/Customer/describe/approvalLayouts",
        uiDetailTemplate: "https://dummy-uri.my.salesforce.com/{ID}",
      },
      label: "Customer",
      custom: false,
      fields: [],
      deletable: true,
      isSubtype: false,
      keyPrefix: "0o6",
      mergeable: false,
      queryable: true,
      createable: true,
      extendedBy: null,
      layoutable: true,
      mruEnabled: true,
      searchable: true,
      updateable: true,
      feedEnabled: false,
      hasSubtypes: false,
      isInterface: false,
      labelPlural: "Customers",
      triggerable: true,
      undeletable: true,
      activateable: false,
      listviewable: null,
      retrieveable: true,
      customSetting: false,
      deepCloneable: false,
      implementedBy: null,
      replicateable: true,
      actionOverrides: [],
      recordTypeInfos: [
        {
          name: "Master",
          urls: {
            layout:
              "/services/data/v53.0/sobjects/Customer/describe/layouts/012964000000000AAA",
          },
          active: true,
          master: true,
          available: true,
          recordTypeId: "012964000000000AAA",
          developerName: "Master",
          defaultRecordTypeMapping: true,
        },
      ],
      supportedScopes: [],
      lookupLayoutable: null,
      namedLayoutInfos: [],
      searchLayoutable: true,
      compactLayoutable: true,
      extendsInterfaces: null,
      childRelationships: [
        {
          field: "SobjectLookupValueId",
          childSObject: "AIInsightValue",
          cascadeDelete: true,
          relationshipName: null,
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "TargetId",
          childSObject: "AIRecordInsight",
          cascadeDelete: true,
          relationshipName: null,
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "PartyRoleId",
          childSObject: "CommSubscriptionConsent",
          cascadeDelete: false,
          relationshipName: "CommSubsConsents",
          restrictedDelete: true,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "PartyRoleId",
          childSObject: "CommSubscriptionConsentChangeEvent",
          cascadeDelete: false,
          relationshipName: null,
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "PartyRoleId",
          childSObject: "ContactPointConsent",
          cascadeDelete: false,
          relationshipName: "ContactPointConsents",
          restrictedDelete: true,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "PartyRoleId",
          childSObject: "ContactPointConsentChangeEvent",
          cascadeDelete: false,
          relationshipName: null,
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "PartyRoleId",
          childSObject: "ContactPointTypeConsent",
          cascadeDelete: false,
          relationshipName: "ContactPointTypeConsents",
          restrictedDelete: true,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "PartyRoleId",
          childSObject: "ContactPointTypeConsentChangeEvent",
          cascadeDelete: false,
          relationshipName: null,
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "ParentId",
          childSObject: "CustomerShare",
          cascadeDelete: true,
          relationshipName: "Shares",
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "ContextRecordId",
          childSObject: "FlowExecutionErrorEvent",
          cascadeDelete: false,
          relationshipName: null,
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "RelatedRecordId",
          childSObject: "FlowRecordRelation",
          cascadeDelete: false,
          relationshipName: null,
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "PartyRoleId",
          childSObject: "PartyConsent",
          cascadeDelete: false,
          relationshipName: "PartyConsents",
          restrictedDelete: true,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "PartyRoleId",
          childSObject: "PartyConsentChangeEvent",
          cascadeDelete: false,
          relationshipName: null,
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "TargetObjectId",
          childSObject: "PendingServiceRoutingInteractionInfo",
          cascadeDelete: true,
          relationshipName: null,
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "TargetObjectId",
          childSObject: "ProcessInstance",
          cascadeDelete: true,
          relationshipName: "ProcessInstances",
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
        {
          field: "TargetObjectId",
          childSObject: "ProcessInstanceHistory",
          cascadeDelete: false,
          relationshipName: "ProcessSteps",
          restrictedDelete: false,
          deprecatedAndHidden: false,
          junctionIdListNames: [],
          junctionReferenceTo: [],
        },
      ],
      associateEntityType: null,
      deprecatedAndHidden: false,
      implementsInterfaces: null,
      associateParentEntity: null,
      defaultImplementation: null,
      networkScopeFieldName: null,
      sobjectDescribeOption: "FULL",
    },
  },
} as const;
