/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface FindRecordsValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record Type
   *
   */
  recordType: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Field Value Types
   *
   */
  fieldValueTypes?:
    | Record<string, string>
    | Array<{ key: string; value: string }>;
  /**
   * Page Size
   *
   */
  pageSize?: string;
  /**
   * Page Number
   *
   */
  pageNumber?: string;
  /**
   * Sort Criteria
   *
   */
  sort?: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Max Records To Fetch
   *
   * @default 20000
   */
  maxRecordsToFetch?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Find Records
 *
 * @description Find and fetch Salesforce records.
 */
export const findRecords = {
  key: "findRecords",
  perform: async <TReturn>(values: FindRecordsValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.findRecords({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    fieldValueTypes: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    pageSize: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    pageNumber: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    sort: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    maxRecordsToFetch: {
      inputType: "string",
      collection: undefined,
      default: `20000`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: [
      {
        Id: "003RM000006pL5gQAE",
        Name: "Acme",
        Phone: "123-456-7890",
        BillingCity: "San Francisco",
        BillingState: "CA",
      },
    ],
  },
} as const;
