/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetAllQueryJobInformationValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Is PK Chunking Enabled
   *
   * @default false
   */
  isPkChunkingEnabled?: boolean;
  /**
   * Job Type
   *
   */
  jobType?: string;
  /**
   * Concurrency Mode
   *
   * @default parallel
   */
  concurrencyMode?: string;
  /**
   * Query Locator
   *
   */
  queryLocator?: string;
}

/**
 * List All Bulk Query Job Information
 *
 * @description Retrieve information about all bulk query jobs in the org.
 */
export const getAllQueryJobInformation = {
  key: "getAllQueryJobInformation",
  perform: async <TReturn>(
    values: GetAllQueryJobInformationValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getAllQueryJobInformation({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    isPkChunkingEnabled: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    jobType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    concurrencyMode: {
      inputType: "string",
      collection: undefined,
      default: `parallel`,
    },
    queryLocator: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      done: false,
      records: [
        {
          id: "750R0000000zhfdIAA",
          state: "JobComplete",
          object: "Account",
          jobType: "V2Query",
          operation: "query",
          apiVersion: 60,
          lineEnding: "LF",
          contentType: "CSV",
          createdById: "005R0000000GiwjIAC",
          createdDate: "2018-12-07T19:58:09.000+0000",
          systemModstamp: "2018-12-07T19:59:14.000+0000",
          columnDelimiter: "COMMA",
          concurrencyMode: "Parallel",
        },
        {
          id: "750R0000000zhjzIAA",
          state: "JobComplete",
          object: "Account",
          jobType: "V2Query",
          operation: "query",
          apiVersion: 60,
          lineEnding: "LF",
          contentType: "CSV",
          createdById: "005R0000000GiwjIAC",
          createdDate: "2018-12-07T20:52:28.000+0000",
          systemModstamp: "2018-12-07T20:53:15.000+0000",
          columnDelimiter: "COMMA",
          concurrencyMode: "Parallel",
        },
      ],
      nextRecordsUrl:
        "/services/data/v60.0/jobs/ingest?queryLocator=01gR0000000opRTIAY-2000",
    },
  },
} as const;
