/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetAttachmentValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * File ID
   *
   */
  fileId: string;
}

/**
 * Get Attachment
 *
 * @description Get a file attachment from an account, opportunity, or contact.
 */
export const getAttachment = {
  key: "getAttachment",
  perform: async <TReturn>(values: GetAttachmentValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getAttachment({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    fileId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      data: [83, 71, 86, 115, 98, 71, 56, 103, 86, 50, 57, 121, 98, 71, 81, 61],
      type: "Buffer",
    },
    contentType: "image/png",
  },
} as const;
