/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetBulkJobValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Bulk Job ID
   *
   */
  bulkJobId: string;
}

/**
 * Get Bulk Job Information
 *
 * @description Retrieve information about a bulk ingest job.
 */
export const getBulkJob = {
  key: "getBulkJob",
  perform: async <TReturn>(values: GetBulkJobValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getBulkJob({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    bulkJobId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      id: "7506g00000DhRA2AAN",
      state: "Open",
      object: "Account",
      jobType: "V2Ingest",
      retries: 0,
      operation: "insert",
      apiVersion: 60,
      contentUrl: "services/data/v60.0/jobs/ingest/7506g00000DhRA2AAN/batches",
      lineEnding: "LF",
      contentType: "CSV",
      createdById: "0056g000005HQPyAAO",
      createdDate: "2018-12-18T22:51:36.000+0000",
      systemModstamp: "2018-12-18T22:51:58.000+0000",
      columnDelimiter: "COMMA",
      concurrencyMode: "Parallel",
      apexProcessingTime: 0,
      totalProcessingTime: 0,
      apiActiveProcessingTime: 0,
    },
  },
} as const;
