/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetCustomerValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record ID
   *
   */
  recordId: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Get Customer
 *
 * @description Retrieve a customer record by ID.
 */
export const getCustomer = {
  key: "getCustomer",
  perform: async <TReturn>(values: GetCustomerValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getCustomer({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      Id: "0o68c000000wk3lAAA",
      Name: "Customer Name",
      OwnerId: "0064c00859AJGN6KPA",
      PartyId: "0PK8c000963oLkUGAU",
      IsDeleted: false,
      attributes: {
        url: "/services/data/v53.0/sobjects/Customer/0o68c000000wk3lAAA",
        type: "Customer",
      },
      CreatedById: "0064c00859AJGN6KPA",
      CreatedDate: "2023-12-14T20:54:21.000+0000",
      LastViewedDate: "2023-12-21T22:23:30.000+0000",
      SystemModstamp: "2023-12-14T20:54:21.000+0000",
      LastModifiedById: "0064c00859AJGN6KPA",
      LastModifiedDate: "2023-12-14T20:54:21.000+0000",
      CustomerStatusType: "Active",
      LastReferencedDate: "2023-12-21T22:23:30.000+0000",
      TotalLifeTimeValue: null,
    },
  },
} as const;
