/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetCurrentUserValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Get Current User
 *
 * @description Retrieve information about the currently authenticated user.
 */
export const getCurrentUser = {
  key: "getCurrentUser",
  perform: async <TReturn>(values: GetCurrentUserValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getCurrentUser({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      id: "https://login.salesforce.com/id/00Z8d000694w9weEAQ/0064c00859AJGN6KPA",
      urls: {
        rest: "https://dummy-uri.my.salesforce.com/services/data/v{version}/",
        feeds:
          "https://dummy-uri.my.salesforce.com/services/data/v{version}/chatter/feeds",
        query:
          "https://dummy-uri.my.salesforce.com/services/data/v{version}/query/",
        users:
          "https://dummy-uri.my.salesforce.com/services/data/v{version}/chatter/users",
        groups:
          "https://dummy-uri.my.salesforce.com/services/data/v{version}/chatter/groups",
        recent:
          "https://dummy-uri.my.salesforce.com/services/data/v{version}/recent/",
        search:
          "https://dummy-uri.my.salesforce.com/services/data/v{version}/search/",
        partner:
          "https://dummy-uri.my.salesforce.com/services/Soap/u/{version}/00Z8d000694w9we",
        profile: "https://dummy-uri.my.salesforce.com/0064c00859AJGN6KPA",
        metadata:
          "https://dummy-uri.my.salesforce.com/services/Soap/m/{version}/00Z8d000694w9we",
        sobjects:
          "https://dummy-uri.my.salesforce.com/services/data/v{version}/sobjects/",
        enterprise:
          "https://dummy-uri.my.salesforce.com/services/Soap/c/{version}/00Z8d000694w9we",
        feed_items:
          "https://dummy-uri.my.salesforce.com/services/data/v{version}/chatter/feed-items",
        tooling_rest:
          "https://dummy-uri.my.salesforce.com/services/data/v{version}/tooling/",
        tooling_soap:
          "https://dummy-uri.my.salesforce.com/services/Soap/T/{version}/00Z8d000694w9we",
        custom_domain: "https://dummy-uri.my.salesforce.com",
        feed_elements:
          "https://dummy-uri.my.salesforce.com/services/data/v{version}/chatter/feed-elements",
      },
      email: "jhon@doe.com",
      active: true,
      locale: "en_US",
      photos: {
        picture: "https://dummy-uri.file.force.com/profilephoto/005/F",
        thumbnail: "https://dummy-uri.file.force.com/profilephoto/005/T",
      },
      status: { body: null, created_date: null },
      user_id: "0064c00859AJGN6KPA",
      addr_zip: null,
      language: "en_US",
      timezone: "America/Los_Angeles",
      username: "jhon@doe.com",
      addr_city: null,
      last_name: "Dev",
      nick_name: "dev",
      user_type: "STANDARD",
      utcOffset: -28800000,
      addr_state: null,
      first_name: "Dev",
      addr_street: null,
      addr_country: "US",
      display_name: "Dev Env",
      mobile_phone: null,
      asserted_user: true,
      email_verified: true,
      organization_id: "00Z8d000694w9weEAQ",
      is_app_installed: true,
      last_modified_date: "2023-10-06T18:48:33Z",
      mobile_phone_verified: false,
      is_lightning_login_user: false,
    },
  },
} as const;
