/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetFlowValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Flow Name
   *
   */
  flowName: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Get Flow
 *
 * @description Get details of a specific Flow by name.
 */
export const getFlow = {
  key: "getFlow",
  perform: async <TReturn>(values: GetFlowValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getFlow({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    flowName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      label: "Example Label",
      loops: [],
      start: {
        object: "Account",
        filters: [],
        connector: {
          targetReference: "Send_Example_Action",
          processMetadataValues: [],
        },
        locationX: 50,
        locationY: 0,
        triggerType: "RecordAfterSave",
        recordTriggerType: "CreateAndUpdate",
        processMetadataValues: [],
      },
      steps: [],
      waits: [],
      stages: [],
      status: "Draft",
      choices: [],
      screens: [],
      formulas: [
        {
          name: "TriggerCondition",
          dataType: "Boolean",
          expression: "true",
          processMetadataValues: [],
        },
      ],
      fullName: "Example_Flow_01",
      subflows: [],
      constants: [],
      decisions: [],
      runInMode: "DefaultMode",
      variables: [
        {
          name: "TriggeringRecord",
          isInput: true,
          dataType: "SObject",
          isOutput: false,
          objectType: "Account",
          isCollection: false,
          processMetadataValues: [],
        },
      ],
      apiVersion: "49.0",
      actionCalls: [
        {
          name: "Send_Example_Action",
          label: "Send Example Action",
          locationX: 176,
          locationY: 158,
          actionName: "Account.Example_Action",
          actionType: "outboundMessage",
          nameSegment: "Account.Example_Action",
          inputParameters: [],
          outputParameters: [],
          flowTransactionModel: "CurrentTransaction",
          processMetadataValues: [],
        },
      ],
      assignments: [],
      description: "Example description",
      processType: "AutoLaunchedFlow",
      environments: "Default",
      recordCreates: [],
      recordDeletes: [],
      recordLookups: [],
      recordUpdates: [],
      textTemplates: [],
      apexPluginCalls: [],
      dynamicChoiceSets: [],
      processMetadataValues: [],
      areMetricsLoggedToDataCloud: "false",
    },
  },
} as const;
