/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetFileValues {
  /**
   * Content Version ID
   *
   */
  contentDocumentId: string;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Get File
 *
 * @description Retrieve a file from Salesforce ContentVersion.
 */
export const getFile = {
  key: "getFile",
  perform: async <TReturn>(values: GetFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    contentDocumentId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      data: [83, 71, 86, 115, 98, 71, 56, 103, 86, 50, 57, 121, 98, 71, 81, 61],
      type: "Buffer",
    },
    contentType: "image/png",
  },
} as const;
