/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetJobSuccessfulRecordResultsValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Bulk Job ID
   *
   */
  bulkJobId: string;
}

/**
 * Get Bulk Job Successful Record Results
 *
 * @description Retrieve the successful record results for a bulk ingest job.
 */
export const getJobSuccessfulRecordResults = {
  key: "getJobSuccessfulRecordResults",
  perform: async <TReturn>(
    values: GetJobSuccessfulRecordResultsValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getJobSuccessfulRecordResults({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    bulkJobId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {},
} as const;
