/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetObjectMetadataByNameValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Metadata Type
   *
   * @default CustomObject
   */
  metadataType?: string;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Object Full Name
   *
   */
  fullName: string;
}

/**
 * Get Object Metadata
 *
 * @description Get the metadata of an object by full name.
 */
export const getObjectMetadataByName = {
  key: "getObjectMetadataByName",
  perform: async <TReturn>(
    values: GetObjectMetadataByNameValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getObjectMetadataByName({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    metadataType: {
      inputType: "string",
      collection: undefined,
      default: `CustomObject`,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    fullName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      id: "",
      type: "CustomObject",
      fileName: "objects/Campaign.object",
      fullName: "Campaign",
      createdById: "0064c00859AJGN6KPA",
      createdDate: "1970-01-01T00:00:00.000Z",
      createdByName: "Dev Env",
      namespacePrefix: "",
      lastModifiedById: "0064c00859AJGN6KPA",
      lastModifiedDate: "1970-01-01T00:00:00.000Z",
      lastModifiedByName: "Dev Env",
    },
  },
} as const;
