/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetQueryJobInformationValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Query Job ID
   *
   */
  queryJobId: string;
}

/**
 * Get Bulk Query Job Information
 *
 * @description Get information about a single bulk query job.
 */
export const getQueryJobInformation = {
  key: "getQueryJobInformation",
  perform: async <TReturn>(
    values: GetQueryJobInformationValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getQueryJobInformation({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    queryJobId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      id: "750R0000000zlh9IAA",
      state: "JobComplete",
      object: "Account",
      jobType: "V2Query",
      retries: 0,
      operation: "query",
      apiVersion: 46,
      lineEnding: "LF",
      contentType: "CSV",
      createdById: "005R0000000GiwjIAC",
      createdDate: "2018-12-10T17:50:19.000+0000",
      systemModstamp: "2018-12-10T17:51:27.000+0000",
      columnDelimiter: "COMMA",
      concurrencyMode: "Parallel",
      totalProcessingTime: 334,
      isPkChunkingSupported: true,
      numberRecordsProcessed: 500,
    },
  },
} as const;
