/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetRecordValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record Type
   *
   */
  recordType: string;
  /**
   * Record ID
   *
   */
  recordId: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Get Record
 *
 * @description Get a single Salesforce record by ID.
 */
export const getRecord = {
  key: "getRecord",
  perform: async <TReturn>(values: GetRecordValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getRecord({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      Id: "003RM000006pL5gQAE",
      Name: "Acme",
      Phone: "123-456-7890",
      BillingCity: "San Francisco",
      BillingState: "CA",
    },
  },
} as const;
