/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { abortBulkJob } from "./abortBulkJob";
import { abortBulkQueryJob } from "./abortBulkQueryJob";
import { activateFlow } from "./activateFlow";
import { addAttachment } from "./addAttachment";
import { addUserPermissionSet } from "./addUserPermissionSet";
import { bulkInsertRecords } from "./bulkInsertRecords";
import { bulkUpsertRecords } from "./bulkUpsertRecords";
import { completeUploadBulkJob } from "./completeUploadBulkJob";
import { compositeRequests } from "./compositeRequests";
import { createAccount } from "./createAccount";
import { createBulkJob } from "./createBulkJob";
import { createBulkQueryJob } from "./createBulkQueryJob";
import { createContact } from "./createContact";
import { createCustomer } from "./createCustomer";
import { createFieldsFromMetadata } from "./createFieldsFromMetadata";
import { createFlow } from "./createFlow";
import { createLead } from "./createLead";
import { createObjectsFromMetadata } from "./createObjectsFromMetadata";
import { createOpportunity } from "./createOpportunity";
import { createProfile } from "./createProfile";
import { createRecord } from "./createRecord";
import { createUser } from "./createUser";
import { createWorkflowOutboundMessage } from "./createWorkflowOutboundMessage";
import { createWorkflowRule } from "./createWorkflowRule";
import { deactivateFlow } from "./deactivateFlow";
import { deleteAccount } from "./deleteAccount";
import { deleteBulkJob } from "./deleteBulkJob";
import { deleteBulkQueryJob } from "./deleteBulkQueryJob";
import { deleteContact } from "./deleteContact";
import { deleteCustomer } from "./deleteCustomer";
import { deleteFlow } from "./deleteFlow";
import { deleteInstancedFlowsAndOutboundMessages } from "./deleteInstancedFlowsAndOutboundMessages";
import { deleteLead } from "./deleteLead";
import { deleteMetadata } from "./deleteMetadata";
import { deleteOpportunity } from "./deleteOpportunity";
import { deleteProfile } from "./deleteProfile";
import { deleteRecord } from "./deleteRecord";
import { deleteWorkflowOutboundMessage } from "./deleteWorkflowOutboundMessage";
import { deleteWorkflowRule } from "./deleteWorkflowRule";
import { describeCustomerSObject } from "./describeCustomerSObject";
import { describeObject } from "./describeObject";
import { describePermissions } from "./describePermissions";
import { findRecord } from "./findRecord";
import { findRecords } from "./findRecords";
import { getAllQueryJobInformation } from "./getAllQueryJobInformation";
import { getAttachment } from "./getAttachment";
import { getBulkJob } from "./getBulkJob";
import { getCurrentUser } from "./getCurrentUser";
import { getCustomer } from "./getCustomer";
import { getFile } from "./getFile";
import { getFlow } from "./getFlow";
import { getJobFailedRecordResults } from "./getJobFailedRecordResults";
import { getJobSuccessfulRecordResults } from "./getJobSuccessfulRecordResults";
import { getObjectMetadataByName } from "./getObjectMetadataByName";
import { getQueryJobInformation } from "./getQueryJobInformation";
import { getQueryJobResults } from "./getQueryJobResults";
import { getRecord } from "./getRecord";
import { listBulkJobs } from "./listBulkJobs";
import { listCompositeResources } from "./listCompositeResources";
import { listContacts } from "./listContacts";
import { listCustomers } from "./listCustomers";
import { listFlows } from "./listFlows";
import { listLeads } from "./listLeads";
import { listObjectMetadata } from "./listObjectMetadata";
import { listOpportunities } from "./listOpportunities";
import { listProfiles } from "./listProfiles";
import { listUsers } from "./listUsers";
import { listWorkflowOutboundMessages } from "./listWorkflowOutboundMessages";
import { listWorkflowRules } from "./listWorkflowRules";
import { query } from "./query";
import { rawRequest } from "./rawRequest";
import { removeUserPermissionSet } from "./removeUserPermissionSet";
import { sendTransactionalEmail } from "./sendTransactionalEmail";
import { subscribeToRecordChange } from "./subscribeToRecordChange";
import { subscribeToRecordChanges } from "./subscribeToRecordChanges";
import { updateAccount } from "./updateAccount";
import { updateContact } from "./updateContact";
import { updateCustomer } from "./updateCustomer";
import { updateFlow } from "./updateFlow";
import { updateLead } from "./updateLead";
import { updateMetadata } from "./updateMetadata";
import { updateOpportunity } from "./updateOpportunity";
import { updateProfile } from "./updateProfile";
import { updateRecord } from "./updateRecord";
import { updateUser } from "./updateUser";
import { uploadFile } from "./uploadFile";
import { uploadJobData } from "./uploadJobData";
import { upsertRecord } from "./upsertRecord";
import { validateConnection } from "./validateConnection";

export default {
  abortBulkJob,
  abortBulkQueryJob,
  activateFlow,
  addAttachment,
  addUserPermissionSet,
  bulkInsertRecords,
  bulkUpsertRecords,
  completeUploadBulkJob,
  compositeRequests,
  createAccount,
  createBulkJob,
  createBulkQueryJob,
  createContact,
  createCustomer,
  createFieldsFromMetadata,
  createFlow,
  createLead,
  createObjectsFromMetadata,
  createOpportunity,
  createProfile,
  createRecord,
  createUser,
  createWorkflowOutboundMessage,
  createWorkflowRule,
  deactivateFlow,
  deleteAccount,
  deleteBulkJob,
  deleteBulkQueryJob,
  deleteContact,
  deleteCustomer,
  deleteFlow,
  deleteInstancedFlowsAndOutboundMessages,
  deleteLead,
  deleteMetadata,
  deleteOpportunity,
  deleteProfile,
  deleteRecord,
  deleteWorkflowOutboundMessage,
  deleteWorkflowRule,
  describeCustomerSObject,
  describeObject,
  describePermissions,
  findRecord,
  findRecords,
  getAllQueryJobInformation,
  getAttachment,
  getBulkJob,
  getCurrentUser,
  getCustomer,
  getFile,
  getFlow,
  getJobFailedRecordResults,
  getJobSuccessfulRecordResults,
  getObjectMetadataByName,
  getQueryJobInformation,
  getQueryJobResults,
  getRecord,
  listBulkJobs,
  listCompositeResources,
  listContacts,
  listCustomers,
  listFlows,
  listLeads,
  listObjectMetadata,
  listOpportunities,
  listProfiles,
  listUsers,
  listWorkflowOutboundMessages,
  listWorkflowRules,
  query,
  rawRequest,
  removeUserPermissionSet,
  sendTransactionalEmail,
  subscribeToRecordChange,
  subscribeToRecordChanges,
  updateAccount,
  updateContact,
  updateCustomer,
  updateFlow,
  updateLead,
  updateMetadata,
  updateOpportunity,
  updateProfile,
  updateRecord,
  updateUser,
  uploadFile,
  uploadJobData,
  upsertRecord,
  validateConnection,
};
