/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListWorkflowOutboundMessagesValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Outbound Messages
 *
 * @description Retrieve all Outbound Messages in the Salesforce org.
 */
export const listWorkflowOutboundMessages = {
  key: "listWorkflowOutboundMessages",
  perform: async <TReturn>(
    values: ListWorkflowOutboundMessagesValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.listWorkflowOutboundMessages({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {},
} as const;
