/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListBulkJobsValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Is PK Chunking Enabled
   *
   * @default false
   */
  isPkChunkingEnabled?: boolean;
  /**
   * Job Type
   *
   */
  jobType?: string;
  /**
   * Locator
   *
   */
  queryLocator?: string;
}

/**
 * List Bulk Jobs
 *
 * @description List all bulk ingest jobs in the org.
 */
export const listBulkJobs = {
  key: "listBulkJobs",
  perform: async <TReturn>(values: ListBulkJobsValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.listBulkJobs({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    isPkChunkingEnabled: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    jobType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    queryLocator: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      done: true,
      records: [
        {
          id: "7506g00000DhRA2AAN",
          state: "Open",
          object: "Account",
          jobType: "V2Ingest",
          retries: 0,
          operation: "insert",
          apiVersion: 60,
          contentUrl:
            "services/data/v60.0/jobs/ingest/7506g00000DhRA2AAN/batches",
          lineEnding: "LF",
          contentType: "CSV",
          createdById: "0056g000005HQPyAAO",
          createdDate: "2018-12-18T22:51:36.000+0000",
          systemModstamp: "2018-12-18T22:51:58.000+0000",
          columnDelimiter: "COMMA",
          concurrencyMode: "Parallel",
          apexProcessingTime: 0,
          totalProcessingTime: 0,
          apiActiveProcessingTime: 0,
        },
        {
          id: "7506g00000DhRA2AAN",
          state: "Open",
          object: "Account",
          jobType: "V2Ingest",
          retries: 0,
          operation: "insert",
          apiVersion: 60,
          contentUrl:
            "services/data/v60.0/jobs/ingest/7506g00000DhRA2AAN/batches",
          lineEnding: "LF",
          contentType: "CSV",
          createdById: "0056g000005HQPyAAO",
          createdDate: "2018-12-18T22:51:36.000+0000",
          systemModstamp: "2018-12-18T22:51:58.000+0000",
          columnDelimiter: "COMMA",
          concurrencyMode: "Parallel",
          apexProcessingTime: 0,
          totalProcessingTime: 0,
          apiActiveProcessingTime: 0,
        },
      ],
      nextRecordsUrl:
        "/services/data/v60.0/jobs/ingest?queryLocator=01gR0000000opRTIAY-2000",
    },
  },
} as const;
