/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListWorkflowRulesValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Workflow Rules
 *
 * @description List all Workflow Rules. Workflow Rules are deprecated by Salesforce; migrate to Flow-based actions.
 */
export const listWorkflowRules = {
  key: "listWorkflowRules",
  perform: async <TReturn>(
    values: ListWorkflowRulesValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.listWorkflowRules({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: [
      {
        id: "01Q8c000001QiFoEAK",
        type: "WorkflowRule",
        fileName: "workflows/Account.workflow",
        fullName: "Account.Vendia-Demo-Hook-0064c00859AJGN6KPA",
        createdById: "0064c00859AJGN6KPA",
        createdDate: "2023-04-28T16:39:49.000Z",
        createdByName: "Dev Env",
        manageableState: "unmanaged",
        namespacePrefix: "",
        lastModifiedById: "0064c00859AJGN6KPA",
        lastModifiedDate: "2023-04-28T16:39:49.000Z",
        lastModifiedByName: "Dev Env",
      },
      {
        id: "01Q8c000002RjGhEAK",
        type: "WorkflowRule",
        fileName: "workflows/Contact.workflow",
        fullName: "Contact.Send-Welcome-Email",
        createdById: "0058c00000AJGN6KPO",
        createdDate: "2023-05-12T10:15:00.000Z",
        createdByName: "Integration Admin",
        manageableState: "unmanaged",
        namespacePrefix: "",
        lastModifiedById: "0064c00859AJGN6KPA",
        lastModifiedDate: "2023-05-12T10:15:00.000Z",
        lastModifiedByName: "Dev Env",
      },
    ],
  },
} as const;
