/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListContactsValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Field Value Types
   *
   */
  fieldValueTypes?:
    | Record<string, string>
    | Array<{ key: string; value: string }>;
  /**
   * Page Size
   *
   */
  pageSize?: string;
  /**
   * Page Number
   *
   */
  pageNumber?: string;
  /**
   * Sort Criteria
   *
   */
  sort?: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Max Records To Fetch
   *
   * @default 20000
   */
  maxRecordsToFetch?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Contacts
 *
 * @description List all contact records.
 */
export const listContacts = {
  key: "listContacts",
  perform: async <TReturn>(values: ListContactsValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.listContacts({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    fieldValueTypes: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    pageSize: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    pageNumber: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    sort: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    maxRecordsToFetch: {
      inputType: "string",
      collection: undefined,
      default: `20000`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: [
      {
        Id: "0034c00000AbCdEFAZ",
        Name: "Jane Smith",
        OwnerId: "0054c00000GhIjKLAZ",
        LastName: "Smith",
        AccountId: null,
        IsDeleted: false,
        attributes: {
          url: "/services/data/v53.0/sobjects/Contact/0034c00000AbCdEFAZ",
          type: "Contact",
        },
        CreatedById: "0054c00000GhIjKLAZ",
        CreatedDate: "2024-10-10T19:13:07.000+0000",
        MasterRecordId: null,
        SystemModstamp: "2024-10-10T19:13:07.000+0000",
        LastModifiedById: "0054c00000GhIjKLAZ",
        LastModifiedDate: "2024-10-10T19:13:07.000+0000",
      },
    ],
  },
} as const;
