/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListCompositeResourcesValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
}

/**
 * List Composite Resources
 *
 * @description Retrieve a list of URIs for available composite resources.
 */
export const listCompositeResources = {
  key: "listCompositeResources",
  perform: async <TReturn>(
    values: ListCompositeResourcesValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.listCompositeResources({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
  },
  examplePayload: {
    data: {
      results: [
        {
          tree: "/services/data/v54.0/composite/tree",
          batch: "/services/data/v54.0/composite/batch",
          graph: "/services/data/v54.0/composite/graph",
          sobjects: "/services/data/v54.0/composite/sobjects",
        },
      ],
      hasErrors: false,
    },
  },
} as const;
