/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListUsersValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Field Value Types
   *
   */
  fieldValueTypes?:
    | Record<string, string>
    | Array<{ key: string; value: string }>;
  /**
   * Page Size
   *
   */
  pageSize?: string;
  /**
   * Page Number
   *
   */
  pageNumber?: string;
  /**
   * Sort Criteria
   *
   */
  sort?: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Max Records To Fetch
   *
   * @default 20000
   */
  maxRecordsToFetch?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Users
 *
 * @description List all user records.
 */
export const listUsers = {
  key: "listUsers",
  perform: async <TReturn>(values: ListUsersValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.listUsers({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    fieldValueTypes: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    pageSize: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    pageNumber: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    sort: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    maxRecordsToFetch: {
      inputType: "string",
      collection: undefined,
      default: `20000`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: [
      {
        Id: "0054c00000GhIjKLAZ",
        Name: "Jane Doe",
        LastName: "Doe",
        Username: "jane.doe@example.com",
        FirstName: "Jane",
        attributes: {
          url: "/services/data/v53.0/sobjects/User/0054c00000GhIjKLAZ",
          type: "User",
        },
        CreatedById: "0054c00000MnPqRSAZ",
        CreatedDate: "2023-06-28T13:02:36.000+0000",
        FullPhotoUrl:
          "https://example-dev-ed.my.salesforce.com/profilephoto/005/F",
        IndividualId: null,
        LastLoginDate: "2024-08-13T14:56:59.000+0000",
        SmallPhotoUrl:
          "https://example-dev-ed.my.salesforce.com/profilephoto/005/T",
        BannerPhotoUrl: "/profilephoto/005/B",
        LastViewedDate: null,
        MediumPhotoUrl:
          "https://example-dev-ed.my.salesforce.com/profilephoto/005/M",
        SystemModstamp: "2024-08-14T06:00:01.000+0000",
        DigestFrequency: "D",
        LastModifiedById: "0054c00000MnPqRSAZ",
        LastModifiedDate: "2023-06-28T14:36:13.000+0000",
        LastReferencedDate: null,
        OutOfOfficeMessage: "",
        SmallBannerPhotoUrl: "/profilephoto/005/D",
        IsProfilePhotoActive: false,
        MediumBannerPhotoUrl: "/profilephoto/005/E",
        IsExtIndicatorVisible: false,
        LastPasswordChangeDate: "2024-08-13T14:45:59.000+0000",
        JigsawImportLimitOverride: 300,
        DefaultGroupNotificationFrequency: "N",
      },
    ],
  },
} as const;
