/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListFlowsValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Flows
 *
 * @description List all Flows in the Salesforce org.
 */
export const listFlows = {
  key: "listFlows",
  perform: async <TReturn>(values: ListFlowsValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.listFlows({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: [
      {
        id: "30100000000000",
        type: "Flow",
        fileName: "flows/My_Flow.flow",
        fullName: "My_Flow",
        createdById: "005000000000000",
        createdDate: "2023-01-01T00:00:00.000Z",
        createdByName: "Admin User",
        manageableState: "unmanaged",
        namespacePrefix: null,
        lastModifiedById: "005000000000000",
        lastModifiedDate: "2023-01-01T00:00:00.000Z",
        lastModifiedByName: "Admin User",
      },
    ],
  },
} as const;
