/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListOpportunitiesValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Field Value Types
   *
   */
  fieldValueTypes?:
    | Record<string, string>
    | Array<{ key: string; value: string }>;
  /**
   * Page Size
   *
   */
  pageSize?: string;
  /**
   * Page Number
   *
   */
  pageNumber?: string;
  /**
   * Sort Criteria
   *
   */
  sort?: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Max Records To Fetch
   *
   * @default 20000
   */
  maxRecordsToFetch?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Opportunities
 *
 * @description List all opportunity records.
 */
export const listOpportunities = {
  key: "listOpportunities",
  perform: async <TReturn>(
    values: ListOpportunitiesValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.listOpportunities({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    fieldValueTypes: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    pageSize: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    pageNumber: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    sort: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    maxRecordsToFetch: {
      inputType: "string",
      collection: undefined,
      default: `20000`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: [
      {
        Id: "0064c00000RsOpQRAZ",
        Name: "Acme Corp Renewal 2022",
        Fiscal: "2022 4",
        OwnerId: "0054c00000GhIjKLAZ",
        AccountId: "0014c00000AbCdEFAZ",
        IsDeleted: false,
        IsPrivate: false,
        PushCount: 0,
        StageName: "Prospecting",
        FiscalYear: 2022,
        attributes: {
          url: "/services/data/v53.0/sobjects/Opportunity/0064c00000RsOpQRAZ",
          type: "Opportunity",
        },
        CreatedById: "0054c00000GhIjKLAZ",
        CreatedDate: "2022-07-27T21:25:04.000+0000",
        Description: null,
        FiscalQuarter: 4,
        SystemModstamp: "2022-07-28T12:49:16.000+0000",
        LastActivityDate: null,
        LastModifiedById: "0054c00000GhIjKLAZ",
        LastModifiedDate: "2022-07-28T12:49:16.000+0000",
        LastStageChangeDate: null,
      },
    ],
  },
} as const;
