/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListCustomersValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Field Value Types
   *
   */
  fieldValueTypes?:
    | Record<string, string>
    | Array<{ key: string; value: string }>;
  /**
   * Page Size
   *
   */
  pageSize?: string;
  /**
   * Page Number
   *
   */
  pageNumber?: string;
  /**
   * Sort Criteria
   *
   */
  sort?: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Max Records To Fetch
   *
   * @default 20000
   */
  maxRecordsToFetch?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Customers
 *
 * @description List all customer records.
 */
export const listCustomers = {
  key: "listCustomers",
  perform: async <TReturn>(values: ListCustomersValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.listCustomers({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    fieldValueTypes: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    pageSize: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    pageNumber: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    sort: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    maxRecordsToFetch: {
      inputType: "string",
      collection: undefined,
      default: `20000`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      done: true,
      records: [
        {
          Id: "0o79c690000wk3qBCD",
          Name: "New Name For Customer",
          OwnerId: "0064c00859AJGN6KPA",
          PartyId: "0PK8c000963oLkUGAU",
          IsDeleted: false,
          attributes: {
            url: "/services/data/v53.0/sobjects/Customer/0o79c690000wk3qBCD",
            type: "Customer",
          },
          CreatedById: "0064c00859AJGN6KPA",
          CreatedDate: "2023-12-14T20:54:50.000+0000",
          LastViewedDate: "2023-12-14T20:54:50.000+0000",
          SystemModstamp: "2023-12-14T20:54:50.000+0000",
          LastModifiedById: "0064c00859AJGN6KPA",
          LastModifiedDate: "2023-12-14T20:54:50.000+0000",
          CustomerStatusType: "Active",
          LastReferencedDate: "2023-12-14T20:54:50.000+0000",
          TotalLifeTimeValue: null,
        },
      ],
      totalSize: 2,
    },
  },
} as const;
