/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface QueryValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * SOQL Query
   *
   */
  queryString: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Query
 *
 * @description Run an SOQL query against Salesforce.
 */
export const query = {
  key: "query",
  perform: async <TReturn>(values: QueryValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.query({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    queryString: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {},
} as const;
