/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface RemoveUserPermissionSetValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * User Name
   *
   */
  userName: string;
  /**
   * Permission Set
   *
   */
  permissionName: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Remove User Permission Set
 *
 * @description Remove a permission set from the specified user.
 */
export const removeUserPermissionSet = {
  key: "removeUserPermissionSet",
  perform: async <TReturn>(
    values: RemoveUserPermissionSetValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.removeUserPermissionSet({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    userName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    permissionName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
