/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface SendTransactionalEmailValues {
  /**
   * Message Key
   *
   */
  messageKey: string;
  /**
   * Definition Key
   *
   */
  definitionKey: string;
  /**
   * Recipient Contact Key
   *
   */
  recipientContactKey: string;
  /**
   * Recipient Email
   *
   */
  recipientEmail: string;
  /**
   * Recipient Attributes
   *
   */
  recipientAttributes?:
    | Record<string, string>
    | Array<{ key: string; value: string }>;
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
}

/**
 * Send Transactional Email
 *
 * @description Send a transactional email message to a single recipient via Salesforce.
 */
export const sendTransactionalEmail = {
  key: "sendTransactionalEmail",
  perform: async <TReturn>(
    values: SendTransactionalEmailValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.sendTransactionalEmail({
      ...values,
    })) as TReturn;
  },
  inputs: {
    messageKey: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    definitionKey: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    recipientContactKey: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    recipientEmail: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    recipientAttributes: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
