/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface SubscribeToRecordChangesValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Prefix
   *
   */
  prefix: string;
  /**
   * Endpoint URL
   *
   */
  endpointUrl: string;
  /**
   * Trigger Record Type
   *
   */
  triggerObject: string;
  /**
   * Trigger On
   *
   * @default CreateAndUpdate
   */
  triggerOn?: string;
  /**
   * Fields
   *
   */
  fields?: Array<string>;
  /**
   * Dynamic Fields
   *
   */
  dynamicFields?: string;
  /**
   * Flow Metadata
   *
   */
  flowMetadata?: string;
  /**
   * Filter Formula
   *
   */
  filterFormula?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Subscribe to Record Changes
 *
 * @description Subscribe to Record Changes in Salesforce using an outbound message action.
 */
export const subscribeToRecordChanges = {
  key: "subscribeToRecordChanges",
  perform: async <TReturn>(
    values: SubscribeToRecordChangesValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.subscribeToRecordChanges({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    prefix: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    endpointUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    triggerObject: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    triggerOn: {
      inputType: "string",
      collection: undefined,
      default: `CreateAndUpdate`,
    },
    fields: {
      inputType: "string",
      collection: "valuelist",
      default: [],
    },
    dynamicFields: {
      inputType: "data",
      collection: undefined,
      default: ``,
    },
    flowMetadata: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    filterFormula: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      errors: [],
      success: true,
      flowFullName: "My_Flow",
      outboundMessageFullName: "My_Flow",
    },
  },
} as const;
