/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface SubscribeToRecordChangeValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Outbound Message Name
   *
   */
  name: string;
  /**
   * Record Type
   *
   */
  recordType: string;
  /**
   * Trigger Event
   *
   * @default onAllChanges
   */
  operation?: string;
  /**
   * Endpoint URL
   *
   */
  endpointUrl: string;
  /**
   * Rule Criteria Filter
   *
   */
  filterCriteria?: string;
  /**
   * Formula
   *
   */
  formulaInput?: string;
  /**
   * Integration User Email
   *
   */
  integrationUserEmail?: string;
  /**
   * Description
   *
   */
  description?: string;
  /**
   * Fields
   *
   */
  fields?: Array<string>;
  /**
   * Dynamic Fields
   *
   */
  dynamicFields?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Subscribe to Record Change
 *
 * @description Create a Workflow Rule to subscribe to record changes in Salesforce. Workflow Rules are deprecated by Salesforce; migrate to Flow-based actions.
 */
export const subscribeToRecordChange = {
  key: "subscribeToRecordChange",
  perform: async <TReturn>(
    values: SubscribeToRecordChangeValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.subscribeToRecordChange({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    name: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    recordType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    operation: {
      inputType: "string",
      collection: undefined,
      default: `onAllChanges`,
    },
    endpointUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    filterCriteria: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    formulaInput: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    integrationUserEmail: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    description: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fields: {
      inputType: "string",
      collection: "valuelist",
      default: [],
    },
    dynamicFields: {
      inputType: "data",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      WorkflowRule: { errors: [], success: true, fullName: "Account.TestRule" },
      WorkflowOutboundMessage: {
        errors: [],
        success: true,
        fullName: "Account.TestRule",
      },
    },
  },
} as const;
