/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UpdateLeadValues {
  /**
   * Record ID
   *
   */
  recordId: string;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Company
   *
   */
  company: string;
  /**
   * Email Address
   *
   */
  email: string;
  /**
   * Lead Status
   *
   */
  leadStatus: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * First Name
   *
   */
  firstName?: string;
  /**
   * Last Name
   *
   */
  lastName?: string;
  /**
   * Title
   *
   */
  title?: string;
  /**
   * Phone
   *
   */
  phone?: string;
  /**
   * Lead Source
   *
   */
  leadSource?: string;
  /**
   * Rating
   *
   */
  rating?: string;
  /**
   * Website
   *
   */
  website?: string;
  /**
   * Street Address
   *
   */
  street?: string;
  /**
   * State
   *
   */
  state?: string;
  /**
   * City
   *
   */
  city?: string;
  /**
   * Postal Code
   *
   */
  postalCode?: string;
  /**
   * Number of Employees
   *
   */
  employeeCount?: string;
  /**
   * Description
   *
   */
  description?: string;
  /**
   * Annual Revenue
   *
   */
  revenue?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Update Lead
 *
 * @description Update a Salesforce lead record.
 */
export const updateLead = {
  key: "updateLead",
  perform: async <TReturn>(values: UpdateLeadValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.updateLead({
      ...values,
    })) as TReturn;
  },
  inputs: {
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    company: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    email: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    leadStatus: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    firstName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    lastName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    title: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    phone: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    leadSource: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    rating: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    website: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    street: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    state: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    city: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    postalCode: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    employeeCount: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    description: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    revenue: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
