/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UpdateProfileValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record ID
   *
   */
  recordId: string;
  /**
   * Name
   *
   */
  name?: string;
  /**
   * Description
   *
   */
  description?: string;
  /**
   * Permissions
   *
   */
  permissions?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Update Profile
 *
 * @description Update a Salesforce profile.
 */
export const updateProfile = {
  key: "updateProfile",
  perform: async <TReturn>(values: UpdateProfileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.updateProfile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    name: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    description: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    permissions: {
      inputType: "data",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
