/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UpdateOpportunityValues {
  /**
   * Record ID
   *
   */
  recordId: string;
  /**
   * Next Step
   *
   */
  nextStep?: string;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Amount
   *
   */
  amount?: string;
  /**
   * Stage
   *
   */
  stage: string;
  /**
   * Account ID
   *
   */
  accountId?: string;
  /**
   * Opportunity Type
   *
   */
  opportunityType: string;
  /**
   * Close Date
   *
   */
  closeDate: string;
  /**
   * Lead Source
   *
   */
  leadSource?: string;
  /**
   * Probability
   *
   */
  probability?: string;
  /**
   * Description
   *
   */
  description?: string;
  /**
   * Name
   *
   */
  name: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Update Opportunity
 *
 * @description Update an existing opportunity record.
 */
export const updateOpportunity = {
  key: "updateOpportunity",
  perform: async <TReturn>(
    values: UpdateOpportunityValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.updateOpportunity({
      ...values,
    })) as TReturn;
  },
  inputs: {
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    nextStep: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    amount: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    stage: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    accountId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    opportunityType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    closeDate: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    leadSource: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    probability: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    description: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    name: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
