/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UpdateMetadataValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Metadata Type
   *
   * @default CustomField
   */
  metadataType?: string;
  /**
   * Metadata
   *
   */
  metadata: string;
}

/**
 * Update Metadata
 *
 * @description Update one or more metadata components.
 */
export const updateMetadata = {
  key: "updateMetadata",
  perform: async <TReturn>(values: UpdateMetadataValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.updateMetadata({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    metadataType: {
      inputType: "string",
      collection: undefined,
      default: `CustomField`,
    },
    metadata: {
      inputType: "code",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: { data: null },
} as const;
