/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UpdateRecordValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record Type
   *
   */
  recordType: string;
  /**
   * Record ID
   *
   */
  recordId: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Update Record
 *
 * @description Update an existing Salesforce record.
 */
export const updateRecord = {
  key: "updateRecord",
  perform: async <TReturn>(values: UpdateRecordValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.updateRecord({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
