/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UpdateAccountValues {
  /**
   * Record ID
   *
   */
  recordId: string;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Phone
   *
   */
  phone?: string;
  /**
   * Website
   *
   */
  website?: string;
  /**
   * Account Type
   *
   */
  type: string;
  /**
   * Industry
   *
   */
  industry: string;
  /**
   * Description
   *
   */
  description?: string;
  /**
   * Number of Employees
   *
   */
  employeeCount?: string;
  /**
   * Annual Revenue
   *
   */
  revenue?: string;
  /**
   * Billing City
   *
   */
  billingCity?: string;
  /**
   * Billing Postal Code
   *
   */
  billingPostalCode?: string;
  /**
   * Billing State
   *
   */
  billingState?: string;
  /**
   * Billing Street Address
   *
   */
  billingStreet?: string;
  /**
   * Billing Country
   *
   */
  billingCountry?: string;
  /**
   * Street Address
   *
   */
  street?: string;
  /**
   * State
   *
   */
  state?: string;
  /**
   * Country
   *
   */
  country?: string;
  /**
   * Name
   *
   */
  name: string;
  /**
   * City
   *
   */
  city?: string;
  /**
   * Postal Code
   *
   */
  postalCode?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Update Account
 *
 * @description Update an existing account record.
 */
export const updateAccount = {
  key: "updateAccount",
  perform: async <TReturn>(values: UpdateAccountValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.updateAccount({
      ...values,
    })) as TReturn;
  },
  inputs: {
    recordId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    phone: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    website: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    type: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    industry: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    description: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    employeeCount: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    revenue: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    billingCity: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    billingPostalCode: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    billingState: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    billingStreet: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    billingCountry: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    street: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    state: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    country: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    name: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    city: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    postalCode: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
