/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UpdateFlowValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Flow Name
   *
   */
  flowName: string;
  /**
   * Description
   *
   */
  description?: string;
  /**
   * Flow Status
   *
   */
  status?: string;
  /**
   * Flow Metadata
   *
   */
  flowMetadata?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Update Flow
 *
 * @description Update an existing Flow in Salesforce by name.
 */
export const updateFlow = {
  key: "updateFlow",
  perform: async <TReturn>(values: UpdateFlowValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.updateFlow({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    flowName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    description: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    status: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    flowMetadata: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: { data: { errors: [], success: true, fullName: "My_Flow" } },
} as const;
