/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UploadFileValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * File
   *
   */
  file: string;
  /**
   * Path On Client
   *
   */
  pathOnClient: string;
}

/**
 * Upload File
 *
 * @description Upload a file to Salesforce ContentVersion.
 */
export const uploadFile = {
  key: "uploadFile",
  perform: async <TReturn>(values: UploadFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.uploadFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    file: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
    pathOnClient: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: { id: "06Q606ExampleId", errors: [], success: true },
  },
} as const;
