/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UpsertRecordValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Record Type
   *
   */
  recordType: string;
  /**
   * External ID Field Name
   *
   */
  externalIdFieldName: string;
  /**
   * Records
   *
   */
  records: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Upsert Record
 *
 * @description Update a Salesforce record if it exists, otherwise create a new Salesforce record.
 */
export const upsertRecord = {
  key: "upsertRecord",
  perform: async <TReturn>(values: UpsertRecordValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.upsertRecord({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    recordType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    externalIdFieldName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    records: {
      inputType: "code",
      collection: undefined,
      default: ``,
      required: true,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: [
      { id: "00190000001pPvHAAU", errors: [], created: true, success: true },
    ],
  },
} as const;
