/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface Oauth2Values {
  /**
   * Scopes
   *
   * @default https:\/\/www.googleapis.com\/auth\/drive https:\/\/www.googleapis.com\/auth\/drive.activity.readonly
   */
  scopes?: string;
  /**
   * Client ID
   *
   */
  clientId: string;
  /**
   * Client Secret
   *
   */
  clientSecret: string;
}

/**
 * OAuth2
 *
 * @comments OAuth2 Connection
 * This object is used to support type hinting.
 */
export const oauth2 = {
  key: "oauth2",
  perform: (_values: Oauth2Values): Promise<void> => Promise.resolve(),
  inputs: {
    scopes: {
      inputType: "string",
      collection: undefined,
      default: `https:\/\/www.googleapis.com\/auth\/drive https:\/\/www.googleapis.com\/auth\/drive.activity.readonly`,
    },
    clientId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    clientSecret: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * OAuth2 Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const googleDriveOauth2 = (
  stableKey: string,
  values: {
    scopes?: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    clientId: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    clientSecret: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  }
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "google-drive",
          true,
          context.componentRegistry
        );
      },
      key: "oauth2",
      values,
    },
  });
};
