/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { selectDrive } from "./selectDrive";
import { selectFiles } from "./selectFiles";
import { selectFolder } from "./selectFolder";

export default {
  selectDrive,
  selectFiles,
  selectFolder,
};
