/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Drive ID
   *
   */
  driveId?: string;
}

/**
 * List Folders
 *
 * @description Lists all available directories
 * This object is used to support type hinting.
 */
export const selectFolder = {
  key: "selectFolder",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    driveId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;

/**
 * List Folders DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const googleDriveSelectFolder = (
  stableKey: string,
  values: {
    connection: ConfigVarExpression;
    driveId?: { value: string } | TemplateExpression | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "google-drive",
          true,
          context.componentRegistry
        );
      },
      key: "selectFolder",
      values,
    },
  });
};
