/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Select Drive
 *
 * @description Select a drive
 * This object is used to support type hinting.
 */
export const selectDrive = {
  key: "selectDrive",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
} as const;

/**
 * Select Drive DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const googleDriveSelectDrive = (
  stableKey: string,
  values: {
    connection: ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "google-drive",
          true,
          context.componentRegistry
        );
      },
      key: "selectDrive",
      values,
    },
  });
};
