/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Drive ID
   *
   */
  driveId?: string;
  /**
   * Query
   *
   */
  query?: string;
  /**
   * Page Size
   *
   * @default 20
   */
  pageSize?: string;
}

/**
 * List Files
 *
 * @description Lists all available files
 * This object is used to support type hinting.
 */
export const selectFiles = {
  key: "selectFiles",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    driveId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    query: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    pageSize: {
      inputType: "string",
      collection: undefined,
      default: `20`,
    },
  },
} as const;

/**
 * List Files DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const googleDriveSelectFiles = (
  stableKey: string,
  values: {
    connection: ConfigVarExpression;
    driveId?: { value: string } | TemplateExpression | ConfigVarExpression;
    query?: { value: string } | TemplateExpression | ConfigVarExpression;
    pageSize?: { value: string } | TemplateExpression | ConfigVarExpression;
  }
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "google-drive",
          true,
          context.componentRegistry
        );
      },
      key: "selectFiles",
      values,
    },
  });
};
