/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type { Connection } from "@prismatic-io/spectral/dist/types";

export interface FlowOutboundMessageTriggerValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Prefix
   *
   */
  prefix: string;
  /**
   * Trigger Record Type
   *
   */
  triggerObject: string;
  /**
   * Trigger On
   *
   * @default CreateAndUpdate
   */
  triggerOn?: string;
  /**
   * Fields
   *
   */
  fields?: Array<string>;
  /**
   * Flow Metadata
   *
   */
  flowMetadata?: string;
  /**
   * Filter Formula
   *
   */
  filterFormula?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Receive Flow-based outbound messages from Salesforce.
 *
 * @description Receive Flow-based outbound messages from Salesforce.
 * This object is used to support type hinting.
 */
export const flowOutboundMessageTrigger = {
  key: "flowOutboundMessageTrigger",
  perform: <TReturn>(
    _values: FlowOutboundMessageTriggerValues
  ): Promise<TReturn> => Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    prefix: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    triggerObject: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    triggerOn: {
      inputType: "string",
      collection: undefined,
      default: `CreateAndUpdate`,
    },
    fields: {
      inputType: "string",
      collection: "valuelist",
      default: [],
    },
    flowMetadata: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    filterFormula: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
} as const;

/**
 * Receive Flow-based outbound messages from Salesforce. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const salesforceFlowOutboundMessageTrigger = (values: {
  version?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  prefix:
    | {
        value: string;
      }
    | ConfigVarExpression;
  triggerObject:
    | {
        value: string;
      }
    | ConfigVarExpression;
  triggerOn?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  fields?:
    | {
        value: Array<string>;
      }
    | ConfigVarExpression;
  flowMetadata?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  filterFormula?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  connection:
    | {
        value: Connection;
      }
    | ConfigVarExpression;
}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "salesforce",
        true,
        context.componentRegistry
      );
    },
    key: "flowOutboundMessageTrigger",
    values,
  } as const;
};
