/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { flowOutboundMessageTrigger } from "./flowOutboundMessageTrigger";
import { pollChangesTrigger } from "./pollChangesTrigger";
import { webhook } from "./webhook";
import { workflowTrigger } from "./workflowTrigger";

export default {
  flowOutboundMessageTrigger,
  pollChangesTrigger,
  webhook,
  workflowTrigger,
};
