/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type { Connection } from "@prismatic-io/spectral/dist/types";

export interface PollChangesTriggerValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Record Type
   *
   */
  recordType: string;
  /**
   * Show New Records
   *
   * @default true
   */
  showNewRecords?: boolean;
  /**
   * Show Updated Records
   *
   * @default true
   */
  showUpdatedRecords?: boolean;
  /**
   * Show Deleted Records
   *
   * @default false
   */
  showDeletedRecords?: boolean;
  /**
   * Selected Fields
   *
   */
  selectedFields?: Array<string>;
  /**
   * Return IDs Only
   *
   * @default false
   */
  returnIdsOnly?: boolean;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Field Value Types
   *
   */
  fieldValueTypes?:
    | Record<string, string>
    | Array<{ key: string; value: string }>;
  /**
   * Max Records To Fetch
   *
   * @default 20000
   */
  maxRecordsToFetch?: string;
}

/**
 * Checks for new, updated, and optionally deleted records in Salesforce on a recurring schedule.
 *
 * @description Checks for new, updated, and optionally deleted records in Salesforce on a recurring schedule.
 * This object is used to support type hinting.
 */
export const pollChangesTrigger = {
  key: "pollChangesTrigger",
  perform: <TReturn>(_values: PollChangesTriggerValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    recordType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    showNewRecords: {
      inputType: "boolean",
      collection: undefined,
      default: `true`,
    },
    showUpdatedRecords: {
      inputType: "boolean",
      collection: undefined,
      default: `true`,
    },
    showDeletedRecords: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    selectedFields: {
      inputType: "string",
      collection: "valuelist",
      default: [],
    },
    returnIdsOnly: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    fieldValueTypes: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    maxRecordsToFetch: {
      inputType: "string",
      collection: undefined,
      default: `20000`,
    },
  },
} as const;

/**
 * Checks for new, updated, and optionally deleted records in Salesforce on a recurring schedule. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const salesforcePollChangesTrigger = (values: {
  connection:
    | {
        value: Connection;
      }
    | ConfigVarExpression;
  recordType:
    | {
        value: string;
      }
    | ConfigVarExpression;
  showNewRecords?:
    | {
        value: boolean;
      }
    | ConfigVarExpression;
  showUpdatedRecords?:
    | {
        value: boolean;
      }
    | ConfigVarExpression;
  showDeletedRecords?:
    | {
        value: boolean;
      }
    | ConfigVarExpression;
  selectedFields?:
    | {
        value: Array<string>;
      }
    | ConfigVarExpression;
  returnIdsOnly?:
    | {
        value: boolean;
      }
    | ConfigVarExpression;
  version?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  dynamicValues?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  fieldValues?:
    | {
        value: Record<string, string> | Array<{ key: string; value: string }>;
      }
    | ConfigVarExpression;
  fieldValueTypes?:
    | {
        value: Record<string, string> | Array<{ key: string; value: string }>;
      }
    | ConfigVarExpression;
  maxRecordsToFetch?:
    | {
        value: string;
      }
    | ConfigVarExpression;
}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "salesforce",
        true,
        context.componentRegistry
      );
    },
    key: "pollChangesTrigger",
    values,
  } as const;
};
