/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";

export interface WebhookValues {}

/**
 * Receive and validate webhook requests from Salesforce for manually configured webhook subscriptions.
 *
 * @description Receive and validate webhook requests from Salesforce for manually configured webhook subscriptions.
 * This object is used to support type hinting.
 */
export const webhook = {
  key: "webhook",
  perform: <TReturn>(_values: WebhookValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {},
} as const;

/**
 * Receive and validate webhook requests from Salesforce for manually configured webhook subscriptions. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const salesforceWebhook = (values: {}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "salesforce",
        true,
        context.componentRegistry
      );
    },
    key: "webhook",
    values,
  } as const;
};
