/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type { Connection } from "@prismatic-io/spectral/dist/types";

export interface WorkflowTriggerValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Record Type
   *
   */
  recordType: string;
  /**
   * Trigger Type
   *
   * @default onAllChanges
   */
  triggerType?: string;
  /**
   * Outbound Message Name
   *
   */
  outboundMessageName: string;
  /**
   * Workflow Rule Name
   *
   */
  workflowRuleName: string;
  /**
   * Description
   *
   */
  description?: string;
  /**
   * Fields
   *
   */
  fields?: Array<string>;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
}

/**
 * Receive workflow rule outbound messages from Salesforce.
 *
 * @description Receive workflow rule outbound messages from Salesforce.
 * This object is used to support type hinting.
 */
export const workflowTrigger = {
  key: "workflowTrigger",
  perform: <TReturn>(_values: WorkflowTriggerValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    recordType: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    triggerType: {
      inputType: "string",
      collection: undefined,
      default: `onAllChanges`,
    },
    outboundMessageName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    workflowRuleName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    description: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fields: {
      inputType: "string",
      collection: "valuelist",
      default: [],
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
  },
} as const;

/**
 * Receive workflow rule outbound messages from Salesforce. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const salesforceWorkflowTrigger = (values: {
  connection:
    | {
        value: Connection;
      }
    | ConfigVarExpression;
  recordType:
    | {
        value: string;
      }
    | ConfigVarExpression;
  triggerType?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  outboundMessageName:
    | {
        value: string;
      }
    | ConfigVarExpression;
  workflowRuleName:
    | {
        value: string;
      }
    | ConfigVarExpression;
  description?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  fields?:
    | {
        value: Array<string>;
      }
    | ConfigVarExpression;
  version?:
    | {
        value: string;
      }
    | ConfigVarExpression;
}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "salesforce",
        true,
        context.componentRegistry
      );
    },
    key: "workflowTrigger",
    values,
  } as const;
};
