/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type { Connection } from "@prismatic-io/spectral/dist/types";

export interface DriveActivityPollingTriggerValues {
  /**
   * Trigger Events
   *
   */
  triggerEvents?: Array<string>;
  /**
   * File ID
   *
   */
  itemName?: string;
  /**
   * Folder or Drive ID
   *
   */
  ancestorName?: string;
  /**
   * Consolidation Strategy
   *
   */
  consolidationStrategy?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Checks for Google Drive activity on a configured schedule. By default yields activity on personal &#39;My Drive&#39;. For activity on a shared drive, specify a shared drive&#39;s folder&#39;s &#39;Folder ID&#39;.
 *
 * @description Checks for Google Drive activity on a configured schedule. By default yields activity on personal 'My Drive'. For activity on a shared drive, specify a shared drive's folder's 'Folder ID'.
 * This object is used to support type hinting.
 */
export const driveActivityPollingTrigger = {
  key: "driveActivityPollingTrigger",
  perform: <TReturn>(
    _values: DriveActivityPollingTriggerValues
  ): Promise<TReturn> => Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    triggerEvents: {
      inputType: "string",
      collection: "valuelist",
      default: [],
    },
    itemName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    ancestorName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    consolidationStrategy: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
} as const;

/**
 * Checks for Google Drive activity on a configured schedule. By default yields activity on personal &#39;My Drive&#39;. For activity on a shared drive, specify a shared drive&#39;s folder&#39;s &#39;Folder ID&#39;. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const googleDriveDriveActivityPollingTrigger = (values: {
  triggerEvents?:
    | {
        value: Array<string>;
      }
    | ConfigVarExpression;
  itemName?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  ancestorName?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  consolidationStrategy?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  connection:
    | {
        value: Connection;
      }
    | ConfigVarExpression;
}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "google-drive",
        true,
        context.componentRegistry
      );
    },
    key: "driveActivityPollingTrigger",
    values,
  } as const;
};
