/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { driveActivityPollingTrigger } from "./driveActivityPollingTrigger";
import { pollChangesTrigger } from "./pollChangesTrigger";
import { pushNotificationWebhook } from "./pushNotificationWebhook";

export default {
  driveActivityPollingTrigger,
  pollChangesTrigger,
  pushNotificationWebhook,
};
