/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type { Connection } from "@prismatic-io/spectral/dist/types";

export interface PollChangesTriggerValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Drive ID
   *
   */
  driveId?: string;
}

/**
 * Checks for new and updated files in a specified drive (or all drives, if omitted) on a configured schedule.
 *
 * @description Checks for new and updated files in a specified drive (or all drives, if omitted) on a configured schedule.
 * This object is used to support type hinting.
 */
export const pollChangesTrigger = {
  key: "pollChangesTrigger",
  perform: <TReturn>(_values: PollChangesTriggerValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    driveId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;

/**
 * Checks for new and updated files in a specified drive (or all drives, if omitted) on a configured schedule. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const googleDrivePollChangesTrigger = (values: {
  connection:
    | {
        value: Connection;
      }
    | ConfigVarExpression;
  driveId?:
    | {
        value: string;
      }
    | ConfigVarExpression;
}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "google-drive",
        true,
        context.componentRegistry
      );
    },
    key: "pollChangesTrigger",
    values,
  } as const;
};
