/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";

export interface PushNotificationWebhookValues {}

/**
 * Receive and validate webhook requests from Google Drive for webhooks you configure.
 *
 * @description Receive and validate webhook requests from Google Drive for webhooks you configure.
 * This object is used to support type hinting.
 */
export const pushNotificationWebhook = {
  key: "pushNotificationWebhook",
  perform: <TReturn>(
    _values: PushNotificationWebhookValues
  ): Promise<TReturn> => Promise.resolve<TReturn>({} as TReturn),
  inputs: {},
} as const;

/**
 * Receive and validate webhook requests from Google Drive for webhooks you configure. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const googleDrivePushNotificationWebhook = (values: {}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "google-drive",
        true,
        context.componentRegistry
      );
    },
    key: "pushNotificationWebhook",
    values,
  } as const;
};
