/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CopyFileValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * File ID
   *
   */
  fileId: string;
  /**
   * File Name
   *
   */
  fileName?: string;
  /**
   * Folder ID
   *
   */
  folderId?: string;
}

/**
 * Copy File
 *
 * @description Copy a file by file id
 */
export const copyFile = {
  key: "copyFile",
  perform: async <TReturn>(values: CopyFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.copyFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    fileId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fileName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    folderId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: { data: { name: "example", description: "example" } },
} as const;
