/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateFolderValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Folder Name
   *
   */
  folderName: string;
  /**
   * Parent Folder Id
   *
   */
  parentFolderId?: string;
}

/**
 * Create Folder
 *
 * @description Create a directory file
 */
export const createFolder = {
  key: "createFolder",
  perform: async <TReturn>(values: CreateFolderValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.createFolder({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    folderName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    parentFolderId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: { data: { name: "example", description: "example" } },
} as const;
