/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateFileValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Parent Folder Id
   *
   */
  folderId?: string;
  /**
   * File Content
   *
   */
  fileContent: string;
  /**
   * File Name
   *
   */
  fileName: string;
  /**
   * Fields
   *
   * @default *
   */
  fields?: string;
}

/**
 * Create File
 *
 * @description Create a new file with content and metadata
 */
export const createFile = {
  key: "createFile",
  perform: async <TReturn>(values: CreateFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.createFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    folderId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fileContent: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fileName: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fields: {
      inputType: "string",
      collection: undefined,
      default: `*`,
    },
  },
  examplePayload: {
    data: {
      id: "id_example",
      kind: "drive#file",
      name: "example",
      mimeType: "example",
      description: "example",
    },
  },
} as const;
