/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateDriveWebhookValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Drive ID
   *
   */
  driveId?: string;
  /**
   * Endpoint
   *
   */
  endpoint: string;
  /**
   * Expiration Time
   *
   */
  expiration?: string;
}

/**
 * Create Webhook for Drive
 *
 * @description Create a webhook to receive notifications of changes with a Google Drive
 */
export const createDriveWebhook = {
  key: "createDriveWebhook",
  perform: async <TReturn>(
    values: CreateDriveWebhookValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.createDriveWebhook({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    driveId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    endpoint: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    expiration: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {},
} as const;
