/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateFileWebhookValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * File or Folder ID
   *
   */
  resourceId: string;
  /**
   * Endpoint
   *
   */
  endpoint: string;
  /**
   * Expiration Time
   *
   */
  expiration?: string;
}

/**
 * Create Webhook for File or Folder
 *
 * @description Create a webhook to receive notifications of changes for a file or folder
 */
export const createFileWebhook = {
  key: "createFileWebhook",
  perform: async <TReturn>(
    values: CreateFileWebhookValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.createFileWebhook({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    resourceId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    endpoint: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    expiration: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {},
} as const;
