/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteFileValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * File ID
   *
   */
  fileId: string;
  /**
   * Fields
   *
   * @default *
   */
  fields?: string;
}

/**
 * Delete File
 *
 * @description Delete a file by file id
 */
export const deleteFile = {
  key: "deleteFile",
  perform: async <TReturn>(values: DeleteFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.deleteFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    fileId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fields: {
      inputType: "string",
      collection: undefined,
      default: `*`,
    },
  },
  examplePayload: {},
} as const;
