/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteWebhookValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Webhook ID
   *
   */
  webhookId: string;
  /**
   * Resource ID
   *
   */
  resourceId: string;
}

/**
 * Delete Webhook
 *
 * @description Stop a webhook channel from sending notifications
 */
export const deleteWebhook = {
  key: "deleteWebhook",
  perform: async <TReturn>(values: DeleteWebhookValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.deleteWebhook({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    webhookId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    resourceId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {},
} as const;
