/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface EmptyTrashValues {
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Empty Trash
 *
 * @description Empty the trash of deleted files
 */
export const emptyTrash = {
  key: "emptyTrash",
  perform: async <TReturn>(values: EmptyTrashValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.emptyTrash({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {},
} as const;
