/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetAboutValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Fields
   *
   * @default *
   */
  fields?: string;
}

/**
 * Get About
 *
 * @description Gets information about the user's Drive, and system capabilities
 */
export const getAbout = {
  key: "getAbout",
  perform: async <TReturn>(values: GetAboutValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.getAbout({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    fields: {
      inputType: "string",
      collection: undefined,
      default: `*`,
    },
  },
  examplePayload: {
    data: {
      user: {
        kind: "example",
        displayName: "example",
        emailAddress: "example@email.com",
      },
    },
  },
} as const;
