/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetCurrentUserValues {
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * Get Current User
 *
 * @description Get the information and metadata of the user that is currently logged in
 */
export const getCurrentUser = {
  key: "getCurrentUser",
  perform: async <TReturn>(values: GetCurrentUserValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.getCurrentUser({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      me: true,
      kind: "drive#user",
      photoLink: "https://lh3.googleusercontent.com/a/Example",
      displayName: "Example User",
      emailAddress: "example@gmail.com",
      permissionId: "12345678901234567890",
    },
  },
} as const;
