/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetFileMetadataValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * File ID
   *
   */
  fileId: string;
  /**
   * Fields
   *
   */
  metadataFields: string;
}

/**
 * Get File Metadata
 *
 * @description Gets a file's metadata and content by ID.
 */
export const getFileMetadata = {
  key: "getFileMetadata",
  perform: async <TReturn>(values: GetFileMetadataValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.getFileMetadata({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    fileId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    metadataFields: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      id: "1t_RTuXpBgBEEC1TfZILWJJSBr2gilSFTyhDO_6RwSBs",
      name: "Fountain AX <> ADP WFN Marketplace Mapping",
      mimeType: "application/vnd.google-apps.spreadsheet",
      thumbnailLink:
        "https://lh3.googleusercontent.com/drive-storage/AJQWtBNQ460KV9YNsFDL_x3WQq6D019SkKdIUuWzGO2YKBSiLOfmFtlunKSyC02yi7bycbMN_n2DB1k7OJ5akXI6ZrQ0s0y6qHOaaTrOJyis6EeSsEnJMrFOeNzzn3jo0kg=s220",
    },
  },
} as const;
