/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetFileValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * File ID
   *
   */
  fileId: string;
  /**
   * Preferred Export Type
   *
   */
  exportType?: string;
}

/**
 * Get File
 *
 * @description Gets a file's metadata and content by ID.
 */
export const getFile = {
  key: "getFile",
  perform: async <TReturn>(values: GetFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.getFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    fileId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    exportType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: { data: [101, 120, 97, 109, 112, 108, 101], type: "Buffer" },
    contentType: "application/octet",
  },
} as const;
