/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { copyFile } from "./copyFile";
import { createDriveWebhook } from "./createDriveWebhook";
import { createFile } from "./createFile";
import { createFileWebhook } from "./createFileWebhook";
import { createFolder } from "./createFolder";
import { deleteFile } from "./deleteFile";
import { deleteWebhook } from "./deleteWebhook";
import { emptyTrash } from "./emptyTrash";
import { getAbout } from "./getAbout";
import { getCurrentUser } from "./getCurrentUser";
import { getFile } from "./getFile";
import { getFileMetadata } from "./getFileMetadata";
import { listChanges } from "./listChanges";
import { listDrives } from "./listDrives";
import { listExportTypes } from "./listExportTypes";
import { listFiles } from "./listFiles";
import { listFolders } from "./listFolders";
import { moveFile } from "./moveFile";
import { queryDriveActivity } from "./queryDriveActivity";
import { rawRequest } from "./rawRequest";
import { searchFiles } from "./searchFiles";
import { searchFolders } from "./searchFolders";
import { updateFile } from "./updateFile";

export default {
  copyFile,
  createDriveWebhook,
  createFile,
  createFileWebhook,
  createFolder,
  deleteFile,
  deleteWebhook,
  emptyTrash,
  getAbout,
  getCurrentUser,
  getFile,
  getFileMetadata,
  listChanges,
  listDrives,
  listExportTypes,
  listFiles,
  listFolders,
  moveFile,
  queryDriveActivity,
  rawRequest,
  searchFiles,
  searchFolders,
  updateFile,
};
