/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListFoldersValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Drive ID
   *
   */
  driveId?: string;
  /**
   * Page Size
   *
   * @default 20
   */
  pageSize?: string;
  /**
   * Page Token
   *
   */
  pageToken?: string;
  /**
   * Fields
   *
   * @default *
   */
  fields?: string;
  /**
   * Folder ID
   *
   */
  folderId?: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
}

/**
 * List Folders
 *
 * @description Lists all available directories
 */
export const listFolders = {
  key: "listFolders",
  perform: async <TReturn>(values: ListFoldersValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.listFolders({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    driveId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    pageSize: {
      inputType: "string",
      collection: undefined,
      default: `20`,
    },
    pageToken: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fields: {
      inputType: "string",
      collection: undefined,
      default: `*`,
    },
    folderId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
  },
  examplePayload: {
    data: { files: [{ name: "example", description: "example" }] },
  },
} as const;
