/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListDrivesValues {
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Drives
 *
 * @description List all drives
 */
export const listDrives = {
  key: "listDrives",
  perform: async <TReturn>(values: ListDrivesValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.listDrives({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {},
} as const;
