/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListChangesValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Drive ID
   *
   */
  driveId?: string;
}

/**
 * List Changes
 *
 * @description List changes made to files in your Google Drive since the last time this step ran (up to 1000)
 */
export const listChanges = {
  key: "listChanges",
  perform: async <TReturn>(values: ListChangesValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.listChanges({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    driveId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      kind: "drive#changeList",
      changes: [
        {
          file: {
            id: "14FSE_ESVGWta4XlzWGHVm0VultNS-1uO",
            kind: "drive#file",
            name: "example.png",
            mimeType: "image/png",
          },
          kind: "drive#change",
          time: "2022-09-20T21:36:23.687Z",
          type: "file",
          fileId: "14FSE_ESVGWta4XlzWGHVm0VultNS-1uO",
          removed: false,
          changeType: "file",
        },
      ],
      newStartPageToken: "247040",
    },
    instanceState: { "example-step-id": "example-new-page-token" },
  },
} as const;
