/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface MoveFileValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * File ID
   *
   */
  fileId: string;
  /**
   * Folder ID
   *
   */
  folderId: string;
}

/**
 * Move File
 *
 * @description Move a file by file ID
 */
export const moveFile = {
  key: "moveFile",
  perform: async <TReturn>(values: MoveFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.moveFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    fileId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    folderId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: { data: { name: "example", description: "example" } },
} as const;
