/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface QueryDriveActivityValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * File ID
   *
   */
  itemName?: string;
  /**
   * Folder or Drive ID
   *
   */
  ancestorName?: string;
  /**
   * Page Token
   *
   */
  pageToken?: string;
  /**
   * Filter
   *
   */
  filter?: string;
  /**
   * Consolidation Strategy
   *
   */
  consolidationStrategy?: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
}

/**
 * Query Drive Activity
 *
 * @description Query past activity in Google Drive.
 */
export const queryDriveActivity = {
  key: "queryDriveActivity",
  perform: async <TReturn>(
    values: QueryDriveActivityValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.queryDriveActivity({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    itemName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    ancestorName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    pageToken: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    filter: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    consolidationStrategy: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
  },
  examplePayload: {
    data: {
      activities: [
        {
          actors: [
            {
              user: {
                knownUser: {
                  personName: "people/114118080512406438242",
                  isCurrentUser: true,
                },
              },
            },
          ],
          actions: [{ detail: { create: { upload: {} } } }],
          targets: [
            {
              driveItem: {
                file: {},
                name: "items/1fs5xXnjTgQP6-p9LMXYX3_i9hjXl2Ump",
                owner: {
                  user: {
                    knownUser: {
                      personName: "people/114118080512406438242",
                      isCurrentUser: true,
                    },
                  },
                },
                title: "untitled text 3.csv",
                mimeType: "text/csv",
                driveFile: {},
              },
            },
          ],
          timestamp: "2025-03-11T15:58:37.276Z",
          primaryActionDetail: { create: { upload: {} } },
        },
      ],
      nextPageToken:
        "CoUBADFn3tFqHUj7yCuV1klvj0yytkQy7+pfLdrj1eepGfjkD3FB5tGKr3KfLViTU1NXF2EPzJADxALt8O7M1rC98LjHnv9YG6Sl5sxU8F7UOYI1nzzpXhFNaxmAnNmlzBbdRHKt33n2KeX/wKd8uvLETNydZ/9SEYYRlB2aIqzTf41Cp2CUvxIMEgppdGVtcy9yb290GoUBADFn3tFN3fZknT3aMUZoAhEoqOy0S2eimkjEsCV1+t01uERxyQKMsgS5Zn9cSJOzDIj2BR7jkbfIQeDbBLgMhjrtaVaAMppVhBOdQKtn9+u5CKE1JNIuVXREsrEago3Bbd77pDvQJNYTIeW0P+NYbPPP7oRCWTbBZ9soopmJnkyjUX/m5A==",
    },
  },
} as const;
