/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UpdateFileValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * File ID
   *
   */
  fileId: string;
  /**
   * File Content
   *
   */
  fileContent?: string;
  /**
   * File Name
   *
   */
  fileName?: string;
  /**
   * Fields
   *
   * @default *
   */
  fields?: string;
}

/**
 * Update File
 *
 * @description Updates a file's content by file id
 */
export const updateFile = {
  key: "updateFile",
  perform: async <TReturn>(values: UpdateFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.googleDrive.updateFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    fileId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fileContent: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fileName: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fields: {
      inputType: "string",
      collection: undefined,
      default: `*`,
    },
  },
  examplePayload: {
    data: {
      id: "id_example",
      kind: "drive#file",
      name: "example",
      mimeType: "example",
      description: "example",
    },
  },
} as const;
